// GENERATED by gen/build.py - do not edit by hand
package com.krolasyon.bosses.morph;

/** ability animation lengths in ticks per form, taken from the generated animations */
public final class FormDurations {
    private FormDurations() {}

    public static final int[][] TICKS = {
            {24, 36, 28, 64, 48},
            {28, 36, 32, 22, 36},
            {52, 32, 32, 44, 44},
            {22, 36, 36, 24, 80},
            {20, 30, 28, 30, 44},
            {26, 26, 28, 32, 68}
    };
}
