// GENERATED by gen/blocks.py - do not edit by hand
package com.krolasyon.bosses.registry;

final class BlockTable {
    private BlockTable() {}

    /** id, hardness, resistance, light, kind */
    static final Object[][] ROWS = {
        {"ashstone", 1.8F, 6.0F, 0, "plain"},
        {"ashstone_bricks", 2.0F, 7.0F, 0, "plain"},
        {"ember_rock", 2.0F, 6.0F, 7, "plain"},
        {"bone_sand", 0.8F, 1.0F, 0, "plain"},
        {"blood_moss", 0.8F, 1.0F, 0, "plain"},
        {"shadow_loam", 1.0F, 1.5F, 0, "plain"},
        {"rot_mud", 0.8F, 1.0F, 0, "plain"},
        {"hellsteel_ore", 3.5F, 6.0F, 0, "ore"},
        {"hellgate_stone", 35.0F, 1200.0F, 4, "plain"},
        {"ember_lamp", 0.5F, 1.0F, 15, "plain"},
        {"soul_lamp", 0.5F, 1.0F, 14, "plain"},
        {"blood_lamp", 0.5F, 1.0F, 14, "plain"},
        {"shadow_lamp", 0.5F, 1.0F, 12, "plain"},
        {"rot_lamp", 0.5F, 1.0F, 14, "plain"},
    };
}
