// GENERATED by gen/build_items.py - do not edit by hand
package com.krolasyon.bosses.registry;

public final class GearTable {
    private GearTable() {}

    /** id, kind, attack bonus, attack speed modifier, rarity, mana cost, cooldown ticks */
    public static final Object[][] ROWS = {
        {"ember_brand", "sword", 5F, -2.4F, "rare", 25, 140},
        {"bone_reaper", "sword", 5F, -2.2F, "rare", 25, 120},
        {"blood_thirst", "sword", 4F, -2.0F, "rare", 20, 160},
        {"shadow_fang", "sword", 3F, -1.6F, "rare", 25, 100},
        {"rot_cleaver", "sword", 6F, -2.8F, "rare", 25, 140},
        {"sealbreaker", "sword", 6F, -2.6F, "epic", 40, 200},
        {"chain_whip", "sword", 3F, -2.0F, "rare", 20, 80},
        {"obsidian_greataxe", "sword", 11F, -3.3F, "epic", 35, 160},
        {"hellfire_scythe", "sword", 6F, -2.5F, "epic", 40, 180},
        {"sovereign_blade", "sword", 9F, -2.2F, "epic", 60, 240},
        {"tome_fireball", "tome", 0F, 0F, "common", 15, 20},
        {"tome_hellrain", "tome", 0F, 0F, "rare", 45, 120},
        {"tome_soul_chain", "tome", 0F, 0F, "uncommon", 25, 60},
        {"tome_blood_pact", "tome", 0F, 0F, "uncommon", 10, 80},
        {"tome_void_step", "tome", 0F, 0F, "rare", 20, 40},
        {"tome_thorn_burst", "tome", 0F, 0F, "uncommon", 20, 50},
        {"tome_bone_prison", "tome", 0F, 0F, "rare", 30, 100},
        {"tome_summon_imp", "tome", 0F, 0F, "uncommon", 35, 200},
        {"tome_decree", "tome", 0F, 0F, "epic", 80, 400},
    };
}
