// GENERATED by gen/build_items.py - do not edit by hand
package com.krolasyon.bosses.registry;

final class MaterialTable {
    private MaterialTable() {}

    /** id, rarity */
    static final String[][] ROWS = {
        {"ember_shard", "common"},
        {"bone_dust", "common"},
        {"blood_vial", "uncommon"},
        {"shadow_essence", "uncommon"},
        {"rot_spore", "common"},
        {"soul_ember", "uncommon"},
        {"raw_hellsteel", "common"},
        {"hellsteel_ingot", "uncommon"},
        {"hellsteel_nugget", "common"},
        {"ember_sigil", "epic"},
        {"bone_sigil", "epic"},
        {"blood_sigil", "epic"},
        {"shadow_sigil", "epic"},
        {"rot_sigil", "epic"},
        {"sovereign_seal", "epic"},
        {"queen_heart", "rare"},
        {"bone_crown", "rare"},
        {"nyx_eye", "rare"},
        {"rot_heart", "rare"},
        {"obsidian_core", "rare"},
        {"ash_crown", "epic"},
        {"hell_spark", "uncommon"},
    };
}
