package com.krolasyon.sololeveling.client.render;

import com.krolasyon.sololeveling.SoloLeveling;
import com.krolasyon.sololeveling.item.SLArmorItem;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.client.extensions.common.IClientItemExtensions;

/** GENERATED by gen/armor.py — custom 3D armor models (horns, plumes, capes, pauldrons). */
public final class ArmorModels {
    public static final ModelLayerLocation MONARCH = new ModelLayerLocation(SoloLeveling.id("armor_monarch"), "main");
    public static final ModelLayerLocation KNIGHT = new ModelLayerLocation(SoloLeveling.id("armor_knight"), "main");
    public static final ModelLayerLocation ORC = new ModelLayerLocation(SoloLeveling.id("armor_orc"), "main");
    public static final ModelLayerLocation HUNTER = new ModelLayerLocation(SoloLeveling.id("armor_hunter"), "main");
    public static final ModelLayerLocation INNER = new ModelLayerLocation(SoloLeveling.id("armor_inner"), "main");

    private ArmorModels() {}

    public static LayerDefinition monarchLayer() {
        MeshDefinition mesh = HumanoidModel.createMesh(new CubeDeformation(1.0F), 0F);
        PartDefinition root = mesh.getRoot();
        root.getChild("head").addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(0, 51).addBox(3F, -11F, -1F, 1F, 5F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.3491F));
        root.getChild("head").addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(4, 51).addBox(-4F, -11F, -1F, 1F, 5F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, -0.3491F));
        root.getChild("head").addOrReplaceChild("crest", CubeListBuilder.create().texOffs(8, 51).addBox(-0.5F, -10.5F, -4.5F, 1F, 3F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("body").addOrReplaceChild("cape", CubeListBuilder.create().texOffs(0, 32).addBox(-4.5F, 0F, 2.6F, 9F, 18F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("right_arm").addOrReplaceChild("pauldron_r", CubeListBuilder.create().texOffs(20, 32).addBox(-4.5F, -3.5F, -3F, 5F, 3F, 6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("left_arm").addOrReplaceChild("pauldron_l", CubeListBuilder.create().texOffs(42, 32).addBox(-0.5F, -3.5F, -3F, 5F, 3F, 6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("right_arm").addOrReplaceChild("spike_r", CubeListBuilder.create().texOffs(12, 51).addBox(-3.5F, -5.5F, -0.5F, 1F, 2F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("left_arm").addOrReplaceChild("spike_l", CubeListBuilder.create().texOffs(16, 51).addBox(2.5F, -5.5F, -0.5F, 1F, 2F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition knightLayer() {
        MeshDefinition mesh = HumanoidModel.createMesh(new CubeDeformation(1.0F), 0F);
        PartDefinition root = mesh.getRoot();
        root.getChild("head").addOrReplaceChild("crest", CubeListBuilder.create().texOffs(30, 32).addBox(-1F, -10.5F, -4.5F, 2F, 2F, 9F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("head").addOrReplaceChild("plume", CubeListBuilder.create().texOffs(20, 32).addBox(-1.5F, -9.5F, 4.0F, 3F, 12F, 2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.3491F, 0.0000F, 0.0000F));
        root.getChild("body").addOrReplaceChild("cape", CubeListBuilder.create().texOffs(0, 32).addBox(-4.5F, 0F, 2.6F, 9F, 16F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("right_arm").addOrReplaceChild("pauldron_r", CubeListBuilder.create().texOffs(0, 49).addBox(-4.5F, -3.5F, -3F, 5F, 4F, 6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("left_arm").addOrReplaceChild("pauldron_l", CubeListBuilder.create().texOffs(22, 49).addBox(-0.5F, -3.5F, -3F, 5F, 4F, 6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition orcLayer() {
        MeshDefinition mesh = HumanoidModel.createMesh(new CubeDeformation(1.0F), 0F);
        PartDefinition root = mesh.getRoot();
        root.getChild("head").addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(44, 32).addBox(4.5F, -9F, -1F, 1F, 4F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.6109F));
        root.getChild("head").addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(48, 32).addBox(-5.5F, -9F, -1F, 1F, 4F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, -0.6109F));
        root.getChild("right_arm").addOrReplaceChild("fur_r", CubeListBuilder.create().texOffs(0, 32).addBox(-4.5F, -3.5F, -3F, 5F, 3F, 6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("left_arm").addOrReplaceChild("fur_l", CubeListBuilder.create().texOffs(22, 32).addBox(-0.5F, -3.5F, -3F, 5F, 3F, 6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("body").addOrReplaceChild("skull", CubeListBuilder.create().texOffs(52, 32).addBox(-1.5F, 2F, -3.2F, 3F, 3F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition hunterLayer() {
        MeshDefinition mesh = HumanoidModel.createMesh(new CubeDeformation(1.0F), 0F);
        PartDefinition root = mesh.getRoot();
        root.getChild("head").addOrReplaceChild("visor", CubeListBuilder.create().texOffs(34, 32).addBox(-4.5F, -6F, -5.2F, 9F, 2F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("body").addOrReplaceChild("pouch_l", CubeListBuilder.create().texOffs(18, 32).addBox(1F, 7F, -3.4F, 3F, 3F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("body").addOrReplaceChild("pouch_r", CubeListBuilder.create().texOffs(26, 32).addBox(-4F, 7F, -3.4F, 3F, 3F, 1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        root.getChild("right_arm").addOrReplaceChild("pad_r", CubeListBuilder.create().texOffs(0, 32).addBox(-3.5F, -2.5F, -2.5F, 4F, 3F, 5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0F, 0F, 0F, 0.0000F, 0.0000F, 0.0000F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition innerLayer() {
        return LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.5F), 0F), 64, 64);
    }

    public static IClientItemExtensions extensions(SLArmorItem.Mat mat) {
        return new IClientItemExtensions() {
            private HumanoidModel<LivingEntity> outer, inner;

            @Override
            public HumanoidModel<?> getHumanoidArmorModel(LivingEntity entity, ItemStack stack, EquipmentSlot slot, HumanoidModel<?> original) {
                var models = Minecraft.getInstance().getEntityModels();
                if (outer == null) {
                    ModelLayerLocation loc = switch (mat) {
                        case SHADOW_MONARCH -> MONARCH;
                        case CRIMSON_KNIGHT -> KNIGHT;
                        case HIGH_ORC -> ORC;
                        case HUNTER -> HUNTER;
                    };
                    outer = new HumanoidModel<>(models.bakeLayer(loc));
                    inner = new HumanoidModel<>(models.bakeLayer(INNER));
                }
                return slot == EquipmentSlot.LEGS ? inner : outer;
            }
        };
    }
}
