// GENERATED by gen/build.py - do not edit by hand
package com.krolasyon.bosses.client.model;

import net.minecraft.client.animation.AnimationDefinition;

public final class FormAnimSets {
    private FormAnimSets() {}

    public static final int IDLE = 0, WALK = 1, RUN = 2, JUMP = 3, FALL = 4, CROUCH = 5, SWIM = 6, ATTACK_R = 7, ATTACK_L = 8, TRANSFORM = 9, DEATH = 10, ABILITY = 11;

    public static final AnimationDefinition[][] SETS = {
            {AigoarAnimations.IDLE, AigoarAnimations.WALK, AigoarAnimations.RUN, AigoarAnimations.JUMP, AigoarAnimations.FALL, AigoarAnimations.CROUCH, AigoarAnimations.SWIM, AigoarAnimations.ATTACK_R, AigoarAnimations.ATTACK_L, AigoarAnimations.TRANSFORM, AigoarAnimations.DEATH, AigoarAnimations.REND, AigoarAnimations.MAELSTROM, AigoarAnimations.GEYSER, AigoarAnimations.BEAM, AigoarAnimations.TSUNAMI},
            {SolarAnimations.IDLE, SolarAnimations.WALK, SolarAnimations.RUN, SolarAnimations.JUMP, SolarAnimations.FALL, SolarAnimations.CROUCH, SolarAnimations.SWIM, SolarAnimations.ATTACK_R, SolarAnimations.ATTACK_L, SolarAnimations.TRANSFORM, SolarAnimations.DEATH, SolarAnimations.ABILITY0, SolarAnimations.ABILITY1, SolarAnimations.ABILITY2, SolarAnimations.ABILITY3, SolarAnimations.ABILITY4},
            {DragonAnimations.IDLE, DragonAnimations.WALK, DragonAnimations.RUN, DragonAnimations.JUMP, DragonAnimations.FALL, DragonAnimations.CROUCH, DragonAnimations.SWIM, DragonAnimations.ATTACK_R, DragonAnimations.ATTACK_L, DragonAnimations.TRANSFORM, DragonAnimations.DEATH, DragonAnimations.ABILITY0, DragonAnimations.ABILITY1, DragonAnimations.ABILITY2, DragonAnimations.ABILITY3, DragonAnimations.ABILITY4},
            {FlameAnimations.IDLE, FlameAnimations.WALK, FlameAnimations.RUN, FlameAnimations.JUMP, FlameAnimations.FALL, FlameAnimations.CROUCH, FlameAnimations.SWIM, FlameAnimations.ATTACK_R, FlameAnimations.ATTACK_L, FlameAnimations.TRANSFORM, FlameAnimations.DEATH, FlameAnimations.ABILITY0, FlameAnimations.ABILITY1, FlameAnimations.ABILITY2, FlameAnimations.ABILITY3, FlameAnimations.ABILITY4},
            {ShadeAnimations.IDLE, ShadeAnimations.WALK, ShadeAnimations.RUN, ShadeAnimations.JUMP, ShadeAnimations.FALL, ShadeAnimations.CROUCH, ShadeAnimations.SWIM, ShadeAnimations.ATTACK_R, ShadeAnimations.ATTACK_L, ShadeAnimations.TRANSFORM, ShadeAnimations.DEATH, ShadeAnimations.ABILITY0, ShadeAnimations.ABILITY1, ShadeAnimations.ABILITY2, ShadeAnimations.ABILITY3, ShadeAnimations.ABILITY4},
            {LancerAnimations.IDLE, LancerAnimations.WALK, LancerAnimations.RUN, LancerAnimations.JUMP, LancerAnimations.FALL, LancerAnimations.CROUCH, LancerAnimations.SWIM, LancerAnimations.ATTACK_R, LancerAnimations.ATTACK_L, LancerAnimations.TRANSFORM, LancerAnimations.DEATH, LancerAnimations.ABILITY0, LancerAnimations.ABILITY1, LancerAnimations.ABILITY2, LancerAnimations.ABILITY3, LancerAnimations.ABILITY4}
    };
}
