modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="sololeveling"
version="1.0.0"
displayName="Solo Leveling: Arise"
authors="krolasyon"
description='''
Solo Leveling: Sistem, Seviye, Golgeler, Kapilar, Zindanlar, Loncalar ve canli bir Kore dunyasi.
'''

[[dependencies.sololeveling]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sololeveling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
