modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/shdtdhdjtddtduddud-ui/krolasyon/issues"

[[mods]]
modId="sololeveling"
version="1.0.0"
displayName="Solo Leveling: Arise"
logoFile="logo.png"
authors="krolasyon"
description='''
Solo Leveling: Sistem penceresi, seviye ve istatistikler, 13 yetenek, golge ordusu (ARISE), Kapilar ve 8 temali zindan, 8 boss, Avci Dunyasi (Seul, Gangnam, Busan, Incheon, Cheju), loncalar, haber agi, gorevler, 3B silah/zirh/iksirler. (Turkce + English)
'''

[[dependencies.sololeveling]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sololeveling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
