modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="krolasyonbosses"
version="2.0.0"
displayName="Krolasyon: Kizil Taht"
authors="krolasyon"
description='''
Kizil Diyar: kendiliginden olusan kizil portallar, 6 biyom ve 5 krallik, 30+ canavar, 6 krallik lordu ve Tiran Azgaroth.
Itibar, ittifak ve fetih siyaseti; hikaye boyunca Kizil Taht'in hukumdari ol. Buyu kitaplari, efsanevi kiliclar, mana ve lutuflar.
Ayrica dort boss: Muhur Bekcisi, Kizil Cehennem Kurdu, Intikam ve Kalp Kirici Iblis.
'''

[[dependencies.krolasyonbosses]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krolasyonbosses]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
