// GENERATED by gen/rpg/javagen.py from gen/rpg/defs.py - do not edit by hand
package com.krolasyon.bosses.rpg.def;

import java.util.*;

public final class RpgDefs {
    private RpgDefs() {}

    public enum Archetype { HUMANOID, BRUTE, QUADRUPED, ARACHNID, INSECT, FLYER, SLIME, SERPENT, GOLEM, FLOATER, TREANT, CRUSTACEAN; }
    public enum Ability { FIREBALL, ICE_SHARD, POISON_SPIT, ACID_SPIT, SHADOW_BOLT, LIGHTNING_ORB, ROCK_THROW, BONE_SPEAR, WATER_JET, ARCANE_MISSILES, BLOOD_BOLT, SPORE_SHOT, WEB_SHOT, HOLY_BOLT, SAND_BLAST, FIRE_NOVA, FROST_NOVA, SHOCKWAVE, POISON_CLOUD, QUAKE, SPORE_BURST, SANDSTORM, THUNDERSTORM, METEOR, ROOTS, VORTEX_PULL, SONIC_SCREAM, FEAR_ROAR, BLIND_FLASH, CURSE, DARK_PULSE, LEAP_SLAM, CHARGE, BLINK_BEHIND, BURROW, DIVE_BOMB, SHADOW_STEP, DODGE, HEAL, ENRAGE, STONE_SKIN, INVISIBILITY, REGEN_AURA, SUMMON, TAIL_SWEEP, SPIN_ATTACK, LIFE_DRAIN, STEAL, GRAB_THROW, BITE_BLEED, FIRE_BREATH, FROST_BREATH, POISON_BREATH; }
    public enum School { FIRE, ICE, LIGHTNING, EARTH, WIND, WATER, LIGHT, DARK, NATURE, ARCANE, BLOOD, SPIRIT; }
    public enum SpellShape { BOLT, BALL, BEAM, CONE, NOVA, RAIN, WALL, BUFF, HEAL, SUMMON, TELEPORT, CHAIN, AURA, TRAP, PULL, STRIKE; }
    public enum SwordPassive { NONE, BURN, FREEZE, SHOCK, POISON, LIFESTEAL, WITHER, BLEED, KNOCKUP, HOLY, EXECUTE, CRIT, MANA_STEAL, SLOW, BLIND, WEAKEN, GIANT_SLAYER, DEMON_SLAYER, UNDEAD_SLAYER, DRAGON_SLAYER; }
    public enum SwordSkill { FLAME_WAVE, FROST_NOVA, THUNDER_STRIKE, POISON_FAN, BLOOD_FRENZY, SHADOW_DASH, WHIRLWIND, GROUND_SLAM, HOLY_SMITE, CRESCENT_SLASH, BLADE_STORM, DRAGON_BREATH, SOUL_REAP, WIND_CUTTER, EARTH_SPLITTER, STAR_FALL, VOID_RIFT, MIRROR_CLONES, BERSERK, WAR_CRY, TIDE_SLASH, METEOR_DROP, PHANTOM_BLADES, ICE_PRISON, CHAIN_SHOCK, LIFE_BLOOM, EXECUTION, ASH_CYCLONE, GRAVITY_CRUSH, SPIRIT_ARMY, SUN_BURST, ROYAL_DECREE; }
    public enum RegionId {
        ALDORIA("Aldoria Ovaları", 0, 1), SYLVARIEN("Gümüşyaprak Ormanı", 1, 2), KHAZDUR("Demirdağlar", 2, 3), INFERNAX("Kül Toprakları", 3, 5), YMIRHEIM("Donuk Zirveler", 4, 4), GORMASH("Kızıl Bozkır", 5, 3), FELARIS("Pençe Vadisi", 6, 2), VALDREN("Kara Sınır", 7, 3), MERIDIA("Altın Kıyılar", 8, 2), NOCTHERA("Gecegölge Vadisi", 9, 4), WOLF_FOREST("Kurtların Ormanı", -1, 2), DEAD_MARSH("Ölüler Bataklığı", -1, 3), DRAGON_TEETH("Ejderdişi Dağları", -1, 4), GLASS_DESERT("Cam Çölü", -1, 3), WHISPER_STEPPE("Fısıltı Bozkırı", -1, 2), CRYSTAL_HOLLOW("Kristal Çukur", -1, 4), CURSED_RUINS("Lanetli Harabeler", -1, 4), STORM_COAST("Fırtına Kıyısı", -1, 3);
        public final String title; public final int kingdom; public final int danger;
        RegionId(String title, int kingdom, int danger) { this.title = title; this.kingdom = kingdom; this.danger = danger; }
        public boolean wild() { return kingdom < 0; }
    }
    public static final int P_HORNS = 1 << 0;
    public static final int P_EARS = 1 << 1;
    public static final int P_TUSKS = 1 << 2;
    public static final int P_SPIKES = 1 << 3;
    public static final int P_TAIL = 1 << 4;
    public static final int P_WINGS = 1 << 5;
    public static final int P_CLAWS = 1 << 6;
    public static final int P_MANE = 1 << 7;
    public static final int P_CROWN = 1 << 8;
    public static final int P_EYES = 1 << 9;
    public static final int P_SHELL = 1 << 10;
    public static final int P_HOOD = 1 << 11;
    public static final String[] PART_NAMES = {"horns", "ears", "tusks", "spikes", "tail", "wings", "claws", "mane", "crown", "eyes", "shell", "hood"};
    public static final int T_FIRE_IMMUNE = 1 << 0;
    public static final int T_SUN_BURN = 1 << 1;
    public static final int T_FLYING = 1 << 2;
    public static final int T_FLOATING = 1 << 3;
    public static final int T_HEAVY = 1 << 4;
    public static final int T_THORNS = 1 << 5;
    public static final int T_REGEN = 1 << 6;
    public static final int T_POISON_TOUCH = 1 << 7;
    public static final int T_FIRE_TOUCH = 1 << 8;
    public static final int T_FROST_TOUCH = 1 << 9;
    public static final int T_WITHER_TOUCH = 1 << 10;
    public static final int T_LIFESTEAL = 1 << 11;
    public static final int T_EXPLODE_DEATH = 1 << 12;
    public static final int T_SPLIT_DEATH = 1 << 13;
    public static final int T_PACK = 1 << 14;
    public static final int T_NIGHT_ONLY = 1 << 15;
    public static final int T_UNDEAD = 1 << 16;
    public static final int T_ARMORED = 1 << 17;
    public static final int T_FAST = 1 << 18;
    public static final int T_EVASIVE = 1 << 19;
    public static final int T_SHOCK_TOUCH = 1 << 20;
    public static final int T_AQUATIC = 1 << 21;

    public static final String[][] SCHOOL_INFO = {{"Ateş", "16738842", "16764992"}, {"Buz", "8444159", "16777215"}, {"Yıldırım", "10535167", "16777215"}, {"Toprak", "9071168", "12623984"}, {"Rüzgar", "13693152", "8437920"}, {"Su", "3178751", "8442111"}, {"Işık", "16773280", "16777215"}, {"Karanlık", "5909130", "1706538"}, {"Doğa", "5292096", "12648320"}, {"Gizem", "12607743", "16748799"}, {"Kan", "12587040", "5898248"}, {"Ruh", "6356960", "13697016"}};
    public static String schoolName(School s) { return SCHOOL_INFO[s.ordinal()][0]; }
    public static int schoolColor(School s) { return Integer.parseInt(SCHOOL_INFO[s.ordinal()][1]); }
    public static int schoolColor2(School s) { return Integer.parseInt(SCHOOL_INFO[s.ordinal()][2]); }

    public static final List<MonsterDef> MONSTERS = new ArrayList<>();
    public static final List<MonsterDef> BOSSES = new ArrayList<>();
    public static final Map<String, MonsterDef> BY_ID = new LinkedHashMap<>();
    public static final List<SpellDef> SPELLS = new ArrayList<>();
    public static final Map<String, SpellDef> SPELL_BY_ID = new LinkedHashMap<>();
    public static final List<SwordDef> SWORDS = new ArrayList<>();

    private static void add(MonsterDef d) { (d.boss() ? BOSSES : MONSTERS).add(d); BY_ID.put(d.id(), d); }
    private static void spell(SpellDef d) { SPELLS.add(d); SPELL_BY_ID.put(d.id(), d); }

    static {
        monsters();
        bosses();
        spells();
        swords();
    }

    private static void monsters() {
        add(new MonsterDef("dire_wolf", "Vahşi Boz Kurt", Archetype.QUADRUPED, 1.1F, 26F, 5F, 0.33D, 0x6B6560, 0x3A3533, 0xE8E0D0, 0xFFD040, P_EARS | P_TAIL, new Ability[]{Ability.BITE_BLEED, Ability.FEAR_ROAR}, T_PACK | T_FAST, new RegionId[]{RegionId.WOLF_FOREST, RegionId.ALDORIA}, 0, null, false, false));
        add(new MonsterDef("shadow_wolf", "Gölge Kurdu", Archetype.QUADRUPED, 1.15F, 30F, 6F, 0.34D, 0x2A2038, 0x120C1C, 0x7A50C0, 0xC070FF, P_EARS | P_TAIL | P_SPIKES, new Ability[]{Ability.SHADOW_STEP, Ability.BITE_BLEED}, T_PACK | T_NIGHT_ONLY, new RegionId[]{RegionId.WOLF_FOREST, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("thornback_boar", "Dikensırt Yaban Domuzu", Archetype.QUADRUPED, 1.0F, 30F, 6F, 0.3D, 0x5A3A26, 0x2E1E14, 0xD8C8A0, 0xFF5030, P_TUSKS | P_SPIKES, new Ability[]{Ability.CHARGE}, T_THORNS, new RegionId[]{RegionId.WOLF_FOREST, RegionId.ALDORIA, RegionId.FELARIS}, 0, null, false, false));
        add(new MonsterDef("moss_bear", "Yosunlu Ayı", Archetype.QUADRUPED, 1.5F, 55F, 9F, 0.27D, 0x4A3A28, 0x3F6A2A, 0x8AA060, 0xFFB030, P_EARS, new Ability[]{Ability.GRAB_THROW, Ability.ENRAGE}, T_HEAVY, new RegionId[]{RegionId.WOLF_FOREST, RegionId.SYLVARIEN}, 0, null, false, false));
        add(new MonsterDef("goblin_raider", "Goblin Yağmacı", Archetype.HUMANOID, 0.7F, 18F, 4F, 0.33D, 0x5D8F3A, 0x4A3020, 0xA09080, 0xFFE030, P_EARS, new Ability[]{Ability.STEAL, Ability.DODGE}, T_PACK | T_FAST, new RegionId[]{RegionId.WOLF_FOREST, RegionId.ALDORIA, RegionId.WHISPER_STEPPE}, 0, null, false, false));
        add(new MonsterDef("goblin_shaman", "Goblin Şaman", Archetype.HUMANOID, 0.72F, 22F, 3F, 0.28D, 0x4F8A4A, 0x7A2A6A, 0xE8E0C8, 0x60FF90, P_EARS | P_HORNS, new Ability[]{Ability.SPORE_SHOT, Ability.REGEN_AURA}, T_PACK, new RegionId[]{RegionId.WOLF_FOREST, RegionId.GORMASH}, 0, null, true, false));
        add(new MonsterDef("werewolf", "Kurtadam", Archetype.BRUTE, 1.2F, 60F, 10F, 0.32D, 0x5A5048, 0x2C2622, 0xE0D8C8, 0xFFE040, P_EARS | P_MANE | P_TAIL, new Ability[]{Ability.LEAP_SLAM, Ability.BITE_BLEED}, T_REGEN | T_NIGHT_ONLY, new RegionId[]{RegionId.WOLF_FOREST, RegionId.VALDREN}, 0, null, false, false));
        add(new MonsterDef("angry_sapling", "Öfkeli Fidan", Archetype.TREANT, 0.8F, 28F, 4F, 0.22D, 0x5A4028, 0x58A038, 0x90C050, 0xFFE080, 0, new Ability[]{Ability.ROOTS, Ability.SPORE_SHOT}, 0, new RegionId[]{RegionId.WOLF_FOREST, RegionId.SYLVARIEN}, 0, null, false, false));
        add(new MonsterDef("venom_spider", "Zehir Örümceği", Archetype.ARACHNID, 1.0F, 24F, 5F, 0.32D, 0x1E2A18, 0x5AC030, 0xD0FF60, 0xFF2020, P_EYES, new Ability[]{Ability.WEB_SHOT, Ability.POISON_SPIT}, T_POISON_TOUCH, new RegionId[]{RegionId.WOLF_FOREST, RegionId.DEAD_MARSH}, 0, null, false, false));
        add(new MonsterDef("owlbear", "Baykuşayı", Archetype.QUADRUPED, 1.4F, 50F, 9F, 0.28D, 0x7A5A3A, 0xC8B090, 0xF0C040, 0xFFA020, P_EARS | P_MANE, new Ability[]{Ability.SONIC_SCREAM, Ability.GRAB_THROW}, T_HEAVY, new RegionId[]{RegionId.WOLF_FOREST, RegionId.FELARIS}, 0, null, false, false));
        add(new MonsterDef("bog_corpse", "Bataklık Cesedi", Archetype.HUMANOID, 1.0F, 26F, 5F, 0.23D, 0x4A5A38, 0x2A3020, 0x8A7A50, 0xB0FF40, 0, new Ability[]{Ability.POISON_CLOUD}, T_UNDEAD | T_SUN_BURN, new RegionId[]{RegionId.DEAD_MARSH, RegionId.CURSED_RUINS}, 0, null, false, false));
        add(new MonsterDef("swamp_hag", "Bataklık Cadısı", Archetype.HUMANOID, 0.95F, 32F, 4F, 0.25D, 0x6A7A50, 0x2A2030, 0xA0A080, 0x80FF40, P_HOOD, new Ability[]{Ability.CURSE, Ability.POISON_SPIT, Ability.SUMMON}, 0, new RegionId[]{RegionId.DEAD_MARSH}, 0, "bog_corpse", true, false));
        add(new MonsterDef("mire_slime", "Çamur Balçığı", Archetype.SLIME, 1.0F, 22F, 4F, 0.26D, 0x5A4A30, 0x3A2E1C, 0x8A7040, 0xFFE080, 0, new Ability[]{Ability.ACID_SPIT}, T_SPLIT_DEATH, new RegionId[]{RegionId.DEAD_MARSH}, 0, null, false, false));
        add(new MonsterDef("leech_serpent", "Sülük Yılan", Archetype.SERPENT, 1.0F, 30F, 5F, 0.28D, 0x3A2A30, 0x8A3040, 0xD06070, 0xFF3040, 0, new Ability[]{Ability.LIFE_DRAIN, Ability.BITE_BLEED}, T_LIFESTEAL | T_AQUATIC, new RegionId[]{RegionId.DEAD_MARSH, RegionId.STORM_COAST}, 0, null, false, false));
        add(new MonsterDef("marsh_troll", "Bataklık Trolü", Archetype.BRUTE, 1.5F, 70F, 10F, 0.25D, 0x4A6A5A, 0x2A3A30, 0x9A8A60, 0xFFC030, P_TUSKS, new Ability[]{Ability.ROCK_THROW, Ability.HEAL}, T_REGEN | T_HEAVY, new RegionId[]{RegionId.DEAD_MARSH}, 0, null, false, false));
        add(new MonsterDef("will_o_wisp", "Fener Ruhu", Archetype.FLOATER, 0.5F, 16F, 4F, 0.3D, 0x60E0FF, 0x2080C0, 0xC0FFFF, 0xFFFFFF, 0, new Ability[]{Ability.BLINK_BEHIND, Ability.ARCANE_MISSILES}, T_FLOATING | T_EVASIVE, new RegionId[]{RegionId.DEAD_MARSH, RegionId.SYLVARIEN}, 0, null, true, false));
        add(new MonsterDef("bone_crawler", "Kemik Sürüngen", Archetype.ARACHNID, 0.85F, 24F, 5F, 0.3D, 0xD8D0B8, 0x8A8070, 0xF0E8D0, 0x40FFE0, 0, new Ability[]{Ability.BONE_SPEAR}, T_UNDEAD, new RegionId[]{RegionId.DEAD_MARSH, RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("plague_toad", "Veba Kurbağası", Archetype.QUADRUPED, 0.9F, 22F, 4F, 0.27D, 0x8A9A30, 0x4A5A18, 0xE0E060, 0xFF8000, 0, new Ability[]{Ability.POISON_SPIT, Ability.LEAP_SLAM}, T_EXPLODE_DEATH, new RegionId[]{RegionId.DEAD_MARSH}, 0, null, false, false));
        add(new MonsterDef("ghoul", "Gulyabani", Archetype.HUMANOID, 1.05F, 30F, 6F, 0.32D, 0x7A8A78, 0x3A403A, 0xC0B8A0, 0xFF3030, P_CLAWS, new Ability[]{Ability.BITE_BLEED, Ability.LEAP_SLAM}, T_UNDEAD | T_FAST, new RegionId[]{RegionId.DEAD_MARSH, RegionId.CURSED_RUINS, RegionId.VALDREN}, 0, null, false, false));
        add(new MonsterDef("drowned_knight", "Boğulmuş Şövalye", Archetype.HUMANOID, 1.1F, 40F, 7F, 0.24D, 0x4A6A6A, 0x3A3020, 0x8A9A90, 0x40FFD0, P_HORNS, new Ability[]{Ability.WATER_JET, Ability.SPIN_ATTACK}, T_UNDEAD | T_ARMORED | T_AQUATIC, new RegionId[]{RegionId.DEAD_MARSH, RegionId.STORM_COAST}, 6, null, true, false));
        add(new MonsterDef("rock_golem", "Kaya Golemi", Archetype.GOLEM, 1.3F, 70F, 10F, 0.2D, 0x7A7670, 0x4A4844, 0xA0D060, 0xFFA020, P_SPIKES, new Ability[]{Ability.QUAKE, Ability.ROCK_THROW}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.KHAZDUR}, 8, null, false, false));
        add(new MonsterDef("harpy", "Harpi", Archetype.FLYER, 1.0F, 24F, 5F, 0.3D, 0xA07850, 0xE0C8A0, 0x504030, 0xFF4040, P_CLAWS, new Ability[]{Ability.DIVE_BOMB, Ability.SONIC_SCREAM}, T_FLYING, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.STORM_COAST}, 0, null, false, false));
        add(new MonsterDef("wyvern", "Wyvern", Archetype.FLYER, 1.6F, 50F, 8F, 0.3D, 0x3A5A30, 0x8A9A50, 0xE0D0A0, 0xFFE020, P_HORNS | P_TAIL, new Ability[]{Ability.POISON_SPIT, Ability.DIVE_BOMB}, T_FLYING, new RegionId[]{RegionId.DRAGON_TEETH}, 0, null, false, false));
        add(new MonsterDef("mountain_ogre", "Dağ Ogresi", Archetype.BRUTE, 1.6F, 75F, 11F, 0.24D, 0xB09070, 0x5A4030, 0x403028, 0xFFD000, P_TUSKS, new Ability[]{Ability.GRAB_THROW, Ability.QUAKE}, T_HEAVY, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.GORMASH}, 0, null, false, false));
        add(new MonsterDef("drake_whelp", "Ejder Yavrusu", Archetype.QUADRUPED, 1.0F, 40F, 7F, 0.3D, 0xA02818, 0xE08030, 0xF0D070, 0xFFE000, P_HORNS | P_WINGS | P_TAIL | P_SPIKES, new Ability[]{Ability.FIRE_BREATH, Ability.LEAP_SLAM}, T_FIRE_IMMUNE, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("storm_eagle", "Fırtına Kartalı", Archetype.FLYER, 1.3F, 30F, 6F, 0.34D, 0x3A5A9A, 0xD0E0FF, 0xF0C040, 0x80E0FF, 0, new Ability[]{Ability.LIGHTNING_ORB, Ability.DIVE_BOMB}, T_FLYING, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.WHISPER_STEPPE, RegionId.STORM_COAST}, 0, null, true, false));
        add(new MonsterDef("cliff_spider", "Uçurum Örümceği", Archetype.ARACHNID, 1.2F, 30F, 6F, 0.33D, 0x6A6460, 0x3A3634, 0xC0B0A0, 0xFF6000, P_EYES, new Ability[]{Ability.WEB_SHOT, Ability.LEAP_SLAM}, 0, new RegionId[]{RegionId.DRAGON_TEETH}, 0, null, false, false));
        add(new MonsterDef("minotaur", "Minotor", Archetype.BRUTE, 1.5F, 80F, 12F, 0.27D, 0x5A3A28, 0x2A1A12, 0xE8E0D0, 0xFF2010, P_HORNS | P_TAIL, new Ability[]{Ability.CHARGE, Ability.SPIN_ATTACK}, T_HEAVY, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.CURSED_RUINS}, 0, null, false, false));
        add(new MonsterDef("griffon", "Grifon", Archetype.QUADRUPED, 1.4F, 45F, 8F, 0.32D, 0xC8A050, 0xF0ECE0, 0x403020, 0xFFC000, P_WINGS | P_TAIL, new Ability[]{Ability.DIVE_BOMB, Ability.SONIC_SCREAM}, T_FLYING, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.MERIDIA}, 0, null, false, false));
        add(new MonsterDef("stone_basilisk", "Taş Bazilisk", Archetype.QUADRUPED, 1.2F, 48F, 8F, 0.24D, 0x5A6A50, 0x8A9070, 0xD0C060, 0xFF00FF, P_SPIKES | P_TAIL | P_CROWN, new Ability[]{Ability.CURSE, Ability.BITE_BLEED}, T_ARMORED, new RegionId[]{RegionId.DRAGON_TEETH, RegionId.GLASS_DESERT}, 6, null, true, false));
        add(new MonsterDef("sand_scorpion", "Kum Akrebi", Archetype.CRUSTACEAN, 1.1F, 32F, 6F, 0.3D, 0xC0A060, 0x7A5A30, 0x402818, 0x200000, P_TAIL | P_CLAWS, new Ability[]{Ability.BITE_BLEED, Ability.BURROW}, T_POISON_TOUCH, new RegionId[]{RegionId.GLASS_DESERT}, 0, null, false, false));
        add(new MonsterDef("dune_worm", "Kum Solucanı", Archetype.SERPENT, 2.0F, 60F, 9F, 0.28D, 0xD0B078, 0x8A6A40, 0xF0E0C0, 0x301008, P_SPIKES, new Ability[]{Ability.BURROW, Ability.QUAKE}, T_HEAVY, new RegionId[]{RegionId.GLASS_DESERT}, 0, null, false, false));
        add(new MonsterDef("mummy", "Mumya", Archetype.HUMANOID, 1.0F, 34F, 6F, 0.22D, 0xD8CCAA, 0x8A7A5A, 0x4A3A2A, 0x40A0FF, 0, new Ability[]{Ability.CURSE, Ability.SANDSTORM}, T_UNDEAD, new RegionId[]{RegionId.GLASS_DESERT, RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("glass_golem", "Cam Golem", Archetype.GOLEM, 1.3F, 55F, 8F, 0.22D, 0xA0E0E0, 0x60A0B0, 0xFFFFFF, 0xFF60FF, P_SPIKES, new Ability[]{Ability.ARCANE_MISSILES, Ability.STONE_SKIN}, T_ARMORED, new RegionId[]{RegionId.GLASS_DESERT}, 10, null, true, false));
        add(new MonsterDef("sand_wraith", "Kum Hayaleti", Archetype.FLOATER, 1.0F, 28F, 6F, 0.3D, 0xD8B880, 0x8A6A40, 0xFFF0C0, 0xFF8020, P_HOOD, new Ability[]{Ability.SANDSTORM, Ability.BLINK_BEHIND}, T_FLOATING | T_UNDEAD, new RegionId[]{RegionId.GLASS_DESERT}, 0, null, true, false));
        add(new MonsterDef("scarab", "Kutsal Bok Böceği", Archetype.INSECT, 0.55F, 12F, 3F, 0.34D, 0x206060, 0x40A080, 0xE0C040, 0xFF2000, P_HORNS, new Ability[]{Ability.BITE_BLEED}, T_PACK | T_FAST, new RegionId[]{RegionId.GLASS_DESERT}, 0, null, false, false));
        add(new MonsterDef("sun_lizard", "Güneş Kertenkelesi", Archetype.QUADRUPED, 0.9F, 26F, 5F, 0.33D, 0xE08020, 0xF0D060, 0xA02010, 0xFFFF00, P_SPIKES | P_TAIL, new Ability[]{Ability.FIRE_BREATH, Ability.DODGE}, T_FIRE_IMMUNE, new RegionId[]{RegionId.GLASS_DESERT, RegionId.MERIDIA}, 0, null, false, false));
        add(new MonsterDef("desert_jackal", "Çöl Çakalı", Archetype.QUADRUPED, 0.85F, 18F, 4F, 0.36D, 0xC09A60, 0x5A4028, 0xF0E0C0, 0xFFD040, P_EARS | P_TAIL, new Ability[]{Ability.BITE_BLEED, Ability.DODGE}, T_PACK | T_FAST, new RegionId[]{RegionId.GLASS_DESERT, RegionId.WHISPER_STEPPE}, 0, null, false, false));
        add(new MonsterDef("sphinx_cat", "Sfenks Kedisi", Archetype.QUADRUPED, 1.2F, 40F, 7F, 0.32D, 0xD0B070, 0x3050A0, 0xF0D040, 0x40C0FF, P_EARS | P_WINGS | P_TAIL | P_CROWN, new Ability[]{Ability.BLIND_FLASH, Ability.LEAP_SLAM}, 0, new RegionId[]{RegionId.GLASS_DESERT}, 0, null, true, false));
        add(new MonsterDef("sand_djinn", "Kum Cini", Archetype.HUMANOID, 1.2F, 45F, 7F, 0.28D, 0x3060C0, 0xE0C060, 0xFFE080, 0xFFFFFF, P_HORNS | P_TAIL, new Ability[]{Ability.SANDSTORM, Ability.FIREBALL}, T_FLOATING, new RegionId[]{RegionId.GLASS_DESERT, RegionId.MERIDIA}, 0, null, true, false));
        add(new MonsterDef("steppe_hyena", "Bozkır Sırtlanı", Archetype.QUADRUPED, 0.95F, 22F, 5F, 0.34D, 0xA08A60, 0x3A3020, 0x5A4A30, 0xFFE020, P_EARS | P_MANE, new Ability[]{Ability.BITE_BLEED, Ability.FEAR_ROAR}, T_PACK, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.GORMASH}, 0, null, false, false));
        add(new MonsterDef("dust_devil", "Toz Şeytanı", Archetype.FLOATER, 1.0F, 24F, 5F, 0.32D, 0xA09070, 0x605040, 0xE0D0B0, 0xFFE0A0, 0, new Ability[]{Ability.VORTEX_PULL, Ability.SANDSTORM}, T_FLOATING | T_EVASIVE, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.GLASS_DESERT}, 0, null, false, false));
        add(new MonsterDef("thunder_bison", "Gök Bizonu", Archetype.QUADRUPED, 1.6F, 65F, 10F, 0.27D, 0x4A3A30, 0x2A2018, 0xA0D0FF, 0x80D0FF, P_HORNS | P_MANE, new Ability[]{Ability.CHARGE, Ability.SHOCKWAVE}, T_HEAVY | T_SHOCK_TOUCH, new RegionId[]{RegionId.WHISPER_STEPPE}, 0, null, true, false));
        add(new MonsterDef("grass_mantis", "Çayır Peygamber Devesi", Archetype.INSECT, 1.1F, 26F, 7F, 0.33D, 0x60A040, 0xA0D060, 0x305020, 0xFFE040, P_CLAWS | P_WINGS, new Ability[]{Ability.SPIN_ATTACK, Ability.LEAP_SLAM}, T_FAST, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.FELARIS}, 0, null, false, false));
        add(new MonsterDef("skyray", "Gök Vatozu", Archetype.FLYER, 1.4F, 30F, 6F, 0.3D, 0x305080, 0xA0C0E0, 0xF0F0FF, 0x80FFFF, P_TAIL, new Ability[]{Ability.LIGHTNING_ORB}, T_FLYING | T_SHOCK_TOUCH, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.STORM_COAST}, 0, null, true, false));
        add(new MonsterDef("bone_vulture", "Kemik Akbaba", Archetype.FLYER, 1.1F, 24F, 5F, 0.32D, 0xD8D0C0, 0x2A2420, 0x8A2020, 0x40FF40, 0, new Ability[]{Ability.DIVE_BOMB, Ability.BONE_SPEAR}, T_FLYING | T_UNDEAD, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("wind_elemental", "Rüzgar Elementali", Archetype.FLOATER, 1.2F, 32F, 6F, 0.34D, 0xD0F0FF, 0x80C0E0, 0xFFFFFF, 0x40A0FF, P_CROWN, new Ability[]{Ability.VORTEX_PULL, Ability.SHOCKWAVE}, T_FLOATING | T_EVASIVE, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.STORM_COAST}, 0, null, true, false));
        add(new MonsterDef("stonehorn_rhino", "Taşboynuz Gergedan", Archetype.QUADRUPED, 1.5F, 70F, 10F, 0.26D, 0x8A8A88, 0x5A5A58, 0xE0D8C0, 0xFF8000, P_HORNS | P_SHELL, new Ability[]{Ability.CHARGE, Ability.STONE_SKIN}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.GORMASH}, 8, null, false, false));
        add(new MonsterDef("plague_rat", "Veba Faresi", Archetype.QUADRUPED, 0.55F, 10F, 3F, 0.35D, 0x5A5048, 0x3A3028, 0xE0A0A0, 0xFF2020, P_EARS | P_TAIL, new Ability[]{Ability.BITE_BLEED}, T_PACK | T_POISON_TOUCH, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.ALDORIA, RegionId.DEAD_MARSH}, 0, null, false, false));
        add(new MonsterDef("scarecrow", "Uğursuz Korkuluk", Archetype.HUMANOID, 1.1F, 28F, 5F, 0.26D, 0xC0A050, 0x6A4A2A, 0xE07010, 0xFF8000, P_HOOD, new Ability[]{Ability.FEAR_ROAR, Ability.BLIND_FLASH}, T_NIGHT_ONLY, new RegionId[]{RegionId.WHISPER_STEPPE, RegionId.ALDORIA}, 0, null, true, false));
        add(new MonsterDef("crystal_spider", "Kristal Örümcek", Archetype.ARACHNID, 1.1F, 30F, 6F, 0.32D, 0x5A3A8A, 0xC080FF, 0xFFD0FF, 0xFF60FF, P_SPIKES | P_EYES, new Ability[]{Ability.ARCANE_MISSILES, Ability.WEB_SHOT}, 0, new RegionId[]{RegionId.CRYSTAL_HOLLOW}, 0, null, true, false));
        add(new MonsterDef("gem_golem", "Mücevher Golemi", Archetype.GOLEM, 1.4F, 75F, 10F, 0.21D, 0x3A3448, 0x60E0A0, 0xFF60A0, 0x60FFFF, P_SPIKES | P_CROWN, new Ability[]{Ability.SHOCKWAVE, Ability.STONE_SKIN}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.KHAZDUR}, 10, null, true, false));
        add(new MonsterDef("cave_troll", "Mağara Trolü", Archetype.BRUTE, 1.5F, 75F, 11F, 0.24D, 0x6A7068, 0x3A3E38, 0xB0A890, 0xFFE040, P_TUSKS | P_SPIKES, new Ability[]{Ability.GRAB_THROW, Ability.ROCK_THROW}, T_REGEN | T_HEAVY | T_SUN_BURN, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.KHAZDUR}, 0, null, false, false));
        add(new MonsterDef("deep_watcher", "Derinlik Gözcüsü", Archetype.FLOATER, 1.1F, 34F, 6F, 0.24D, 0x4A2A3A, 0x8A3A5A, 0xF0E0E0, 0xFFD000, P_EYES, new Ability[]{Ability.BLIND_FLASH, Ability.SHADOW_BOLT}, T_FLOATING, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("crystal_slime", "Kristal Balçık", Archetype.SLIME, 1.0F, 26F, 5F, 0.26D, 0xFF80C0, 0xA040A0, 0xFFE0FF, 0xFFFFFF, 0, new Ability[]{Ability.ARCANE_MISSILES}, T_SPLIT_DEATH, new RegionId[]{RegionId.CRYSTAL_HOLLOW}, 0, null, true, false));
        add(new MonsterDef("echo_bat", "Yankı Yarasası", Archetype.FLYER, 0.6F, 12F, 3F, 0.36D, 0x3A3040, 0x6A5A70, 0xC0A0D0, 0x60FFFF, P_EARS, new Ability[]{Ability.SONIC_SCREAM}, T_FLYING | T_PACK, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("mushroom_brute", "Mantar Devi", Archetype.BRUTE, 1.4F, 60F, 8F, 0.22D, 0xD8C8B0, 0xC02820, 0xF0F0E0, 0x60FF60, P_HOOD, new Ability[]{Ability.SPORE_BURST, Ability.REGEN_AURA}, T_REGEN, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.SYLVARIEN}, 0, null, true, false));
        add(new MonsterDef("lava_salamander", "Lav Semenderi", Archetype.QUADRUPED, 1.1F, 36F, 7F, 0.3D, 0x3A1A10, 0xFF6010, 0xFFD040, 0xFFFF60, P_SPIKES | P_TAIL, new Ability[]{Ability.FIRE_BREATH, Ability.FIRE_NOVA}, T_FIRE_IMMUNE | T_FIRE_TOUCH, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("tunnel_worm", "Tünel Kurdu", Archetype.SERPENT, 1.3F, 40F, 7F, 0.26D, 0xC0A090, 0x6A4A40, 0xF0E0D0, 0x200000, P_SPIKES, new Ability[]{Ability.BURROW, Ability.ACID_SPIT}, 0, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.KHAZDUR}, 0, null, false, false));
        add(new MonsterDef("kobold_miner", "Kobold Madenci", Archetype.HUMANOID, 0.65F, 16F, 4F, 0.32D, 0xB04020, 0x5A4A3A, 0xE0D0B0, 0xFFE000, P_HORNS | P_TAIL, new Ability[]{Ability.ROCK_THROW, Ability.STEAL}, T_PACK, new RegionId[]{RegionId.CRYSTAL_HOLLOW, RegionId.KHAZDUR}, 0, null, false, false));
        add(new MonsterDef("skeleton_legionary", "İskelet Lejyoner", Archetype.HUMANOID, 1.05F, 32F, 7F, 0.26D, 0xE0D8C0, 0x8A2020, 0xC0A040, 0x40FFFF, P_CROWN, new Ability[]{Ability.SPIN_ATTACK, Ability.BONE_SPEAR}, T_UNDEAD | T_ARMORED, new RegionId[]{RegionId.CURSED_RUINS, RegionId.VALDREN}, 6, null, true, false));
        add(new MonsterDef("wraith", "Hortlak", Archetype.FLOATER, 1.1F, 30F, 7F, 0.3D, 0x3A4048, 0x101418, 0x80A0B0, 0x80FFFF, P_HOOD, new Ability[]{Ability.LIFE_DRAIN, Ability.BLINK_BEHIND}, T_UNDEAD | T_FLOATING | T_EVASIVE, new RegionId[]{RegionId.CURSED_RUINS, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("lich_acolyte", "Lich Çırağı", Archetype.HUMANOID, 1.0F, 34F, 5F, 0.25D, 0x2A1A3A, 0xC0B8A0, 0x7040C0, 0xA060FF, P_HOOD, new Ability[]{Ability.SHADOW_BOLT, Ability.SUMMON}, T_UNDEAD, new RegionId[]{RegionId.CURSED_RUINS}, 0, "skeleton_legionary", true, false));
        add(new MonsterDef("banshee", "Feryatçı Ruh", Archetype.FLOATER, 1.0F, 28F, 6F, 0.32D, 0xC0D8E0, 0x6A8090, 0xFFFFFF, 0x40E0FF, P_HOOD, new Ability[]{Ability.SONIC_SCREAM, Ability.FEAR_ROAR}, T_UNDEAD | T_FLOATING, new RegionId[]{RegionId.CURSED_RUINS, RegionId.DEAD_MARSH}, 0, null, true, false));
        add(new MonsterDef("cursed_armor", "Lanetli Zırh", Archetype.HUMANOID, 1.15F, 50F, 9F, 0.24D, 0x3A3A42, 0x1A1A20, 0x6A0A10, 0xFF2020, P_HORNS | P_SPIKES, new Ability[]{Ability.CHARGE, Ability.DARK_PULSE}, T_ARMORED | T_HEAVY, new RegionId[]{RegionId.CURSED_RUINS, RegionId.VALDREN}, 12, null, true, false));
        add(new MonsterDef("gargoyle", "Gargoyl", Archetype.FLYER, 1.2F, 45F, 8F, 0.28D, 0x6A6A70, 0x3A3A40, 0x9A9AA0, 0xFF4000, P_HORNS | P_TAIL | P_CLAWS, new Ability[]{Ability.DIVE_BOMB, Ability.STONE_SKIN}, T_FLYING | T_ARMORED, new RegionId[]{RegionId.CURSED_RUINS, RegionId.VALDREN}, 8, null, true, false));
        add(new MonsterDef("bone_hound", "Kemik Tazısı", Archetype.QUADRUPED, 1.0F, 26F, 6F, 0.34D, 0xE0D8C0, 0x3A3430, 0x8A1010, 0x40FF80, P_SPIKES | P_TAIL, new Ability[]{Ability.BITE_BLEED, Ability.DARK_PULSE}, T_UNDEAD | T_PACK, new RegionId[]{RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("vampire_bat", "Vampir Yarasa", Archetype.FLYER, 0.8F, 18F, 4F, 0.36D, 0x3A1018, 0x8A1020, 0xE0C0C0, 0xFF2020, P_EARS, new Ability[]{Ability.LIFE_DRAIN}, T_FLYING | T_LIFESTEAL | T_PACK, new RegionId[]{RegionId.CURSED_RUINS, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("grave_digger", "Mezar Kazıcı", Archetype.BRUTE, 1.2F, 50F, 8F, 0.24D, 0x5A5A50, 0x2A2420, 0x8A7A60, 0xFFE080, P_HOOD, new Ability[]{Ability.BURROW, Ability.QUAKE}, T_UNDEAD, new RegionId[]{RegionId.CURSED_RUINS, RegionId.DEAD_MARSH}, 0, null, false, false));
        add(new MonsterDef("shadow_stalker", "Gölge Avcı", Archetype.HUMANOID, 1.05F, 30F, 8F, 0.34D, 0x14101C, 0x2A2038, 0x6040A0, 0xFF40FF, P_HOOD | P_CLAWS, new Ability[]{Ability.SHADOW_STEP, Ability.INVISIBILITY}, T_NIGHT_ONLY | T_FAST, new RegionId[]{RegionId.CURSED_RUINS, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("blood_zealot", "Kan Tarikatı Fanatiği", Archetype.HUMANOID, 1.0F, 30F, 6F, 0.28D, 0x6A1018, 0x2A0A0C, 0xC0A040, 0xFF2020, P_HOOD, new Ability[]{Ability.BLOOD_BOLT, Ability.ENRAGE}, 0, new RegionId[]{RegionId.CURSED_RUINS, RegionId.ALDORIA, RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("flesh_golem", "Et Golemi", Archetype.GOLEM, 1.3F, 70F, 10F, 0.22D, 0xC08A80, 0x6A3A3A, 0x3A3A3A, 0xFFE060, P_SPIKES, new Ability[]{Ability.GRAB_THROW, Ability.POISON_CLOUD}, T_REGEN | T_HEAVY, new RegionId[]{RegionId.CURSED_RUINS}, 0, null, false, false));
        add(new MonsterDef("kraken_spawn", "Kraken Yavrusu", Archetype.FLOATER, 1.1F, 36F, 6F, 0.28D, 0x6A2A5A, 0xC06090, 0xF0D0E0, 0xFFE000, P_EYES, new Ability[]{Ability.WATER_JET, Ability.VORTEX_PULL}, T_FLOATING | T_AQUATIC, new RegionId[]{RegionId.STORM_COAST}, 0, null, false, false));
        add(new MonsterDef("siren", "Siren", Archetype.HUMANOID, 1.0F, 30F, 5F, 0.28D, 0x60A0A0, 0x206060, 0xF0E0C0, 0x80FFFF, P_EARS | P_TAIL, new Ability[]{Ability.SONIC_SCREAM, Ability.CURSE}, T_AQUATIC, new RegionId[]{RegionId.STORM_COAST, RegionId.MERIDIA}, 0, null, true, false));
        add(new MonsterDef("giant_crab", "Dev Yengeç", Archetype.CRUSTACEAN, 1.3F, 50F, 9F, 0.24D, 0xC04020, 0x8A2010, 0xF0D0A0, 0x101010, P_CLAWS | P_SHELL | P_EYES, new Ability[]{Ability.GRAB_THROW, Ability.STONE_SKIN}, T_ARMORED | T_AQUATIC, new RegionId[]{RegionId.STORM_COAST, RegionId.MERIDIA}, 10, null, false, false));
        add(new MonsterDef("sea_serpent", "Deniz Yılanı", Archetype.SERPENT, 1.7F, 55F, 9F, 0.3D, 0x205A8A, 0x60C0C0, 0xF0F0D0, 0xFFE000, P_HORNS | P_SPIKES, new Ability[]{Ability.WATER_JET, Ability.TAIL_SWEEP}, T_AQUATIC, new RegionId[]{RegionId.STORM_COAST}, 0, null, false, false));
        add(new MonsterDef("storm_elemental", "Fırtına Elementali", Archetype.FLOATER, 1.3F, 40F, 7F, 0.3D, 0x30305A, 0x6A6AA0, 0xA0E0FF, 0xFFFFFF, P_CROWN | P_SPIKES, new Ability[]{Ability.THUNDERSTORM, Ability.LIGHTNING_ORB}, T_FLOATING | T_SHOCK_TOUCH, new RegionId[]{RegionId.STORM_COAST}, 0, null, true, false));
        add(new MonsterDef("fishman", "Balık Adam", Archetype.HUMANOID, 0.95F, 22F, 5F, 0.3D, 0x4A8A6A, 0xC0D8A0, 0xE08040, 0xFFFF40, P_SPIKES | P_EARS, new Ability[]{Ability.WATER_JET, Ability.SPIN_ATTACK}, T_PACK | T_AQUATIC, new RegionId[]{RegionId.STORM_COAST, RegionId.MERIDIA}, 0, null, false, false));
        add(new MonsterDef("coral_golem", "Mercan Golemi", Archetype.GOLEM, 1.3F, 60F, 9F, 0.21D, 0xE06080, 0xF0A0A0, 0x60C0E0, 0x80FFFF, P_SPIKES, new Ability[]{Ability.SHOCKWAVE, Ability.WATER_JET}, T_THORNS | T_ARMORED | T_AQUATIC, new RegionId[]{RegionId.STORM_COAST}, 6, null, true, false));
        add(new MonsterDef("sea_witch", "Deniz Cadısı", Archetype.HUMANOID, 1.0F, 32F, 5F, 0.26D, 0x305A6A, 0x102A30, 0xA0FFE0, 0x40FFC0, P_HOOD | P_TAIL, new Ability[]{Ability.FROST_NOVA, Ability.CURSE}, T_AQUATIC, new RegionId[]{RegionId.STORM_COAST}, 0, null, true, false));
        add(new MonsterDef("thunder_jelly", "Şimşek Denizanası", Archetype.FLOATER, 0.9F, 20F, 5F, 0.24D, 0xA0C0FF, 0x6080FF, 0xFFFFFF, 0xFFFFFF, 0, new Ability[]{Ability.LIGHTNING_ORB, Ability.SHOCKWAVE}, T_FLOATING | T_SHOCK_TOUCH, new RegionId[]{RegionId.STORM_COAST}, 0, null, true, false));
        add(new MonsterDef("pirate_ghost", "Korsan Hayaleti", Archetype.HUMANOID, 1.0F, 32F, 7F, 0.3D, 0x40A0A0, 0x1A3A3A, 0xE0C040, 0x80FFFF, P_HOOD, new Ability[]{Ability.SPIN_ATTACK, Ability.BLINK_BEHIND}, T_UNDEAD, new RegionId[]{RegionId.STORM_COAST, RegionId.MERIDIA}, 0, null, true, false));
        add(new MonsterDef("frost_wolf", "Ayaz Kurdu", Archetype.QUADRUPED, 1.15F, 30F, 6F, 0.34D, 0xE8F0F8, 0xA0C0E0, 0x4080C0, 0x40C0FF, P_EARS | P_TAIL | P_MANE, new Ability[]{Ability.FROST_BREATH, Ability.BITE_BLEED}, T_PACK | T_FROST_TOUCH, new RegionId[]{RegionId.YMIRHEIM}, 0, null, true, false));
        add(new MonsterDef("yeti", "Yeti", Archetype.BRUTE, 1.6F, 80F, 11F, 0.26D, 0xF0F0F0, 0xA0B0C0, 0x3A4A5A, 0x40A0FF, P_HORNS | P_MANE, new Ability[]{Ability.ROCK_THROW, Ability.FEAR_ROAR}, T_HEAVY | T_FROST_TOUCH, new RegionId[]{RegionId.YMIRHEIM}, 0, null, false, false));
        add(new MonsterDef("ice_wraith", "Buz Hayaleti", Archetype.FLOATER, 1.1F, 30F, 6F, 0.3D, 0xC0E8FF, 0x6090C0, 0xFFFFFF, 0x80FFFF, P_HOOD | P_CROWN, new Ability[]{Ability.ICE_SHARD, Ability.FROST_NOVA}, T_FLOATING | T_UNDEAD, new RegionId[]{RegionId.YMIRHEIM}, 0, null, true, false));
        add(new MonsterDef("frost_troll", "Buz Trolü", Archetype.BRUTE, 1.5F, 75F, 11F, 0.24D, 0x7AA0C0, 0x3A5A7A, 0xE0F0FF, 0x80E0FF, P_TUSKS | P_SPIKES, new Ability[]{Ability.QUAKE, Ability.FROST_NOVA}, T_REGEN | T_HEAVY, new RegionId[]{RegionId.YMIRHEIM}, 0, null, false, false));
        add(new MonsterDef("snow_owl", "Kar Baykuşu", Archetype.FLYER, 0.9F, 20F, 5F, 0.34D, 0xF8F8F8, 0xD0D8E0, 0x303030, 0xFFD000, P_EARS, new Ability[]{Ability.ICE_SHARD, Ability.DIVE_BOMB}, T_FLYING, new RegionId[]{RegionId.YMIRHEIM}, 0, null, false, false));
        add(new MonsterDef("ice_golem", "Buz Golemi", Archetype.GOLEM, 1.4F, 70F, 10F, 0.2D, 0xA0D8FF, 0x6090C0, 0xFFFFFF, 0x2060FF, P_SPIKES | P_CROWN, new Ability[]{Ability.FROST_NOVA, Ability.STONE_SKIN}, T_HEAVY | T_ARMORED | T_FROST_TOUCH, new RegionId[]{RegionId.YMIRHEIM}, 8, null, true, false));
        add(new MonsterDef("woolly_mammoth", "Yünlü Mamut", Archetype.QUADRUPED, 2.0F, 100F, 12F, 0.24D, 0x6A4A30, 0x3A2818, 0xF0E8D8, 0x101010, P_TUSKS | P_MANE, new Ability[]{Ability.CHARGE, Ability.QUAKE}, T_HEAVY, new RegionId[]{RegionId.YMIRHEIM}, 0, null, false, false));
        add(new MonsterDef("imp", "İmp", Archetype.HUMANOID, 0.6F, 16F, 4F, 0.34D, 0xC02818, 0x3A0A08, 0xF0C040, 0xFFFF00, P_HORNS | P_WINGS | P_TAIL, new Ability[]{Ability.FIREBALL, Ability.BLINK_BEHIND}, T_FIRE_IMMUNE | T_FLYING | T_PACK, new RegionId[]{RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("hellhound", "Cehennem Tazısı", Archetype.QUADRUPED, 1.15F, 34F, 7F, 0.34D, 0x1A1010, 0xA01808, 0xFF8020, 0xFFA000, P_SPIKES | P_TAIL | P_EARS, new Ability[]{Ability.FIRE_BREATH, Ability.BITE_BLEED}, T_FIRE_IMMUNE | T_PACK | T_FIRE_TOUCH, new RegionId[]{RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("magma_slime", "Magma Balçığı", Archetype.SLIME, 1.1F, 28F, 6F, 0.26D, 0x5A1A0A, 0xFF6010, 0xFFE060, 0xFFFF80, 0, new Ability[]{Ability.FIRE_NOVA}, T_SPLIT_DEATH | T_FIRE_IMMUNE | T_FIRE_TOUCH, new RegionId[]{RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("ash_golem", "Kül Golemi", Archetype.GOLEM, 1.5F, 80F, 11F, 0.2D, 0x3A3434, 0x1A1414, 0xFF5010, 0xFFA020, P_SPIKES | P_HORNS, new Ability[]{Ability.METEOR, Ability.FIRE_NOVA}, T_FIRE_IMMUNE | T_HEAVY, new RegionId[]{RegionId.INFERNAX}, 6, null, true, false));
        add(new MonsterDef("succubus", "Sukkubus", Archetype.HUMANOID, 1.0F, 36F, 6F, 0.3D, 0xD06070, 0x2A0A18, 0x1A1A1A, 0xFF40A0, P_HORNS | P_WINGS | P_TAIL, new Ability[]{Ability.LIFE_DRAIN, Ability.CURSE}, T_FIRE_IMMUNE | T_LIFESTEAL, new RegionId[]{RegionId.INFERNAX, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("bone_drake", "Kemik Ejderi", Archetype.QUADRUPED, 1.5F, 60F, 10F, 0.3D, 0xD8D0B8, 0x3A3A30, 0x40A040, 0x40FF40, P_HORNS | P_WINGS | P_TAIL | P_SPIKES, new Ability[]{Ability.POISON_BREATH, Ability.TAIL_SWEEP}, T_UNDEAD | T_FLYING, new RegionId[]{RegionId.INFERNAX, RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("fire_beetle", "Ateş Böceği", Archetype.INSECT, 0.8F, 18F, 4F, 0.3D, 0x3A1A0A, 0xFF6010, 0xFFC040, 0xFFFF40, P_HORNS | P_SHELL, new Ability[]{Ability.FIRE_NOVA}, T_EXPLODE_DEATH | T_FIRE_IMMUNE, new RegionId[]{RegionId.INFERNAX, RegionId.GLASS_DESERT}, 0, null, true, false));
        add(new MonsterDef("pit_fiend", "Çukur Zebanisi", Archetype.BRUTE, 1.7F, 90F, 13F, 0.25D, 0x8A1010, 0x2A0606, 0x1A1A1A, 0xFFD000, P_HORNS | P_WINGS | P_TAIL, new Ability[]{Ability.GRAB_THROW, Ability.FIRE_NOVA}, T_FIRE_IMMUNE | T_HEAVY, new RegionId[]{RegionId.INFERNAX}, 6, null, true, false));
        add(new MonsterDef("lava_serpent", "Lav Yılanı", Archetype.SERPENT, 1.5F, 50F, 9F, 0.28D, 0x2A0A06, 0xFF4010, 0xFFE060, 0xFFFF60, P_SPIKES | P_HORNS, new Ability[]{Ability.FIREBALL, Ability.BURROW}, T_FIRE_IMMUNE, new RegionId[]{RegionId.INFERNAX}, 0, null, true, false));
        add(new MonsterDef("night_weaver", "Gece Dokuyucu", Archetype.ARACHNID, 1.3F, 40F, 7F, 0.32D, 0x1A1428, 0x4A3A7A, 0xC0A0FF, 0xC040FF, P_SPIKES | P_EYES, new Ability[]{Ability.WEB_SHOT, Ability.SHADOW_STEP}, T_NIGHT_ONLY, new RegionId[]{RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("void_eye", "Boşluk Gözü", Archetype.FLOATER, 1.2F, 40F, 7F, 0.24D, 0x1A0A2A, 0x5A2A8A, 0xE0D0FF, 0xFF00FF, P_EYES | P_SPIKES, new Ability[]{Ability.DARK_PULSE, Ability.VORTEX_PULL}, T_FLOATING, new RegionId[]{RegionId.NOCTHERA, RegionId.CURSED_RUINS}, 0, null, true, false));
        add(new MonsterDef("nightmare_steed", "Kabus Atı", Archetype.QUADRUPED, 1.4F, 50F, 9F, 0.36D, 0x101010, 0x2A0A3A, 0xA040FF, 0xFF40FF, P_MANE | P_TAIL | P_HORNS, new Ability[]{Ability.CHARGE, Ability.FEAR_ROAR}, T_FAST, new RegionId[]{RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("mind_flayer", "Zihin Yiyici", Archetype.HUMANOID, 1.05F, 40F, 6F, 0.26D, 0x8A6A9A, 0x3A2A4A, 0xD0A0D0, 0xFFFFFF, P_HOOD | P_TUSKS, new Ability[]{Ability.CURSE, Ability.SHADOW_BOLT}, 0, new RegionId[]{RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("umbral_moth", "Gölge Güvesi", Archetype.INSECT, 1.0F, 22F, 4F, 0.3D, 0x3A3050, 0x8070C0, 0xF0E0FF, 0x80FFFF, P_WINGS | P_EYES, new Ability[]{Ability.BLIND_FLASH, Ability.SPORE_BURST}, T_FLYING, new RegionId[]{RegionId.NOCTHERA, RegionId.SYLVARIEN}, 0, null, true, false));
        add(new MonsterDef("dark_dryad", "Kara Dryad", Archetype.TREANT, 1.0F, 36F, 6F, 0.26D, 0x2A2030, 0x6A2A6A, 0xFF60C0, 0xFF40FF, P_CROWN, new Ability[]{Ability.ROOTS, Ability.LIFE_DRAIN}, T_REGEN, new RegionId[]{RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("corrupted_unicorn", "Kirlenmiş Tekboynuz", Archetype.QUADRUPED, 1.3F, 50F, 8F, 0.36D, 0xE0D8F0, 0x4A2A6A, 0xC040FF, 0xFF40FF, P_HORNS | P_MANE | P_TAIL, new Ability[]{Ability.CHARGE, Ability.DARK_PULSE}, T_FAST, new RegionId[]{RegionId.SYLVARIEN, RegionId.NOCTHERA}, 0, null, true, false));
        add(new MonsterDef("wicked_pixie", "Kötücül Peri", Archetype.FLYER, 0.4F, 10F, 3F, 0.36D, 0xA0FF80, 0xFFA0F0, 0xFFFFFF, 0xFFFFFF, P_EARS | P_WINGS, new Ability[]{Ability.ARCANE_MISSILES, Ability.BLINK_BEHIND}, T_FLYING | T_EVASIVE | T_PACK, new RegionId[]{RegionId.SYLVARIEN}, 0, null, true, false));
        add(new MonsterDef("thorn_treant", "Diken Ağaç Adam", Archetype.TREANT, 1.5F, 80F, 11F, 0.2D, 0x4A3020, 0x2A6A20, 0xA0E040, 0xFF8000, P_SPIKES, new Ability[]{Ability.ROOTS, Ability.SHOCKWAVE}, T_THORNS | T_HEAVY, new RegionId[]{RegionId.SYLVARIEN, RegionId.FELARIS}, 0, null, true, false));
        add(new MonsterDef("moss_slime", "Yosun Balçığı", Archetype.SLIME, 0.9F, 18F, 3F, 0.26D, 0x60B040, 0x306020, 0xC0F080, 0xFFFF80, 0, new Ability[]{Ability.SPORE_SHOT}, T_SPLIT_DEATH, new RegionId[]{RegionId.SYLVARIEN, RegionId.FELARIS}, 0, null, false, false));
        add(new MonsterDef("rust_monster", "Pas Canavarı", Archetype.INSECT, 1.1F, 32F, 5F, 0.28D, 0xA04A20, 0x5A2A10, 0xE0A040, 0x60FF60, P_HORNS | P_TAIL, new Ability[]{Ability.ACID_SPIT, Ability.CHARGE}, T_ARMORED, new RegionId[]{RegionId.KHAZDUR}, 6, null, false, false));
        add(new MonsterDef("clockwork_sentinel", "Kurmalı Bekçi", Archetype.GOLEM, 1.2F, 60F, 9F, 0.24D, 0xB08A40, 0x5A4A30, 0x40C0FF, 0x40E0FF, P_CROWN | P_EYES, new Ability[]{Ability.LIGHTNING_ORB, Ability.CHARGE}, T_ARMORED | T_HEAVY | T_SHOCK_TOUCH, new RegionId[]{RegionId.KHAZDUR, RegionId.MERIDIA}, 10, null, true, false));
        add(new MonsterDef("cave_bear", "Mağara Ayısı", Archetype.QUADRUPED, 1.5F, 60F, 10F, 0.27D, 0x3A2A20, 0x1A1410, 0xA09080, 0xFF6000, P_EARS, new Ability[]{Ability.GRAB_THROW, Ability.ENRAGE}, T_HEAVY, new RegionId[]{RegionId.KHAZDUR, RegionId.YMIRHEIM}, 0, null, false, false));
        add(new MonsterDef("warg", "Varg", Archetype.QUADRUPED, 1.35F, 40F, 8F, 0.35D, 0x2A2420, 0x5A3020, 0xE0D0C0, 0xFF2000, P_EARS | P_MANE | P_TAIL, new Ability[]{Ability.CHARGE, Ability.BITE_BLEED}, T_PACK, new RegionId[]{RegionId.GORMASH, RegionId.VALDREN}, 0, null, false, false));
        add(new MonsterDef("red_vulture", "Kızıl Akbaba", Archetype.FLYER, 1.0F, 20F, 5F, 0.33D, 0x8A2A1A, 0x3A1A10, 0xE0C0A0, 0xFFE000, 0, new Ability[]{Ability.DIVE_BOMB, Ability.BITE_BLEED}, T_FLYING | T_PACK, new RegionId[]{RegionId.GORMASH}, 0, null, false, false));
        add(new MonsterDef("saber_tiger", "Kılıçdiş Kaplan", Archetype.QUADRUPED, 1.3F, 45F, 9F, 0.36D, 0xE08A20, 0x1A1410, 0xF8F0E0, 0x80FF40, P_TUSKS | P_TAIL | P_EARS, new Ability[]{Ability.LEAP_SLAM, Ability.BITE_BLEED}, T_FAST, new RegionId[]{RegionId.FELARIS}, 0, null, false, false));
        add(new MonsterDef("jungle_python", "Dev Piton", Archetype.SERPENT, 1.6F, 50F, 8F, 0.27D, 0x5A6A20, 0xC0A040, 0x2A3010, 0xFFD000, 0, new Ability[]{Ability.ROOTS, Ability.BITE_BLEED}, 0, new RegionId[]{RegionId.FELARIS}, 0, null, false, false));
        add(new MonsterDef("stone_ape", "Taş Goril", Archetype.BRUTE, 1.4F, 70F, 10F, 0.28D, 0x3A3A3A, 0x6A6A68, 0xC0B8A8, 0xFF8000, P_MANE, new Ability[]{Ability.QUAKE, Ability.ROCK_THROW}, T_HEAVY, new RegionId[]{RegionId.FELARIS, RegionId.DRAGON_TEETH}, 0, null, false, false));
        add(new MonsterDef("carrion_crow", "Leş Kargası", Archetype.FLYER, 0.6F, 12F, 3F, 0.36D, 0x14141A, 0x2A2A3A, 0x6A6A80, 0xFF2020, 0, new Ability[]{Ability.DIVE_BOMB, Ability.BLIND_FLASH}, T_FLYING | T_PACK, new RegionId[]{RegionId.VALDREN, RegionId.CURSED_RUINS}, 0, null, false, false));
        add(new MonsterDef("war_ghoul", "Savaş Leşçisi", Archetype.BRUTE, 1.3F, 55F, 9F, 0.28D, 0x5A6050, 0x3A2A20, 0x8A8A8A, 0xFF4040, P_SPIKES | P_CLAWS, new Ability[]{Ability.LEAP_SLAM, Ability.BITE_BLEED}, T_UNDEAD, new RegionId[]{RegionId.VALDREN}, 0, null, false, false));
        add(new MonsterDef("sewer_rat_king", "Lağım Faresi", Archetype.QUADRUPED, 0.7F, 14F, 3F, 0.34D, 0x4A4038, 0x6A5A50, 0xE0B0B0, 0xFF4040, P_EARS | P_TAIL, new Ability[]{Ability.BITE_BLEED, Ability.DODGE}, T_PACK, new RegionId[]{RegionId.ALDORIA, RegionId.MERIDIA}, 0, null, false, false));
        add(new MonsterDef("plains_slime", "Ova Balçığı", Archetype.SLIME, 0.9F, 16F, 3F, 0.26D, 0x60A0FF, 0x3060C0, 0xC0E0FF, 0xFFFFFF, 0, new Ability[]{Ability.WATER_JET}, T_SPLIT_DEATH, new RegionId[]{RegionId.ALDORIA, RegionId.MERIDIA}, 0, null, false, false));
        add(new MonsterDef("highway_ghost", "Yol Hayaleti", Archetype.FLOATER, 1.0F, 22F, 5F, 0.3D, 0xA0B8C0, 0x506068, 0xE0F0FF, 0x80FFFF, P_HOOD, new Ability[]{Ability.FEAR_ROAR, Ability.LIFE_DRAIN}, T_FLOATING | T_UNDEAD | T_NIGHT_ONLY, new RegionId[]{RegionId.ALDORIA, RegionId.VALDREN}, 0, null, true, false));
        add(new MonsterDef("golden_mimic", "Altın Taklitçi", Archetype.GOLEM, 0.9F, 40F, 8F, 0.28D, 0xA07030, 0xF0C040, 0x5A3010, 0xFF2020, P_TUSKS, new Ability[]{Ability.STEAL, Ability.LEAP_SLAM}, T_ARMORED, new RegionId[]{RegionId.MERIDIA, RegionId.CRYSTAL_HOLLOW}, 8, null, false, false));
    }

    private static void bosses() {
        add(new MonsterDef("wolf_king_fenrath", "Kurt Kral Fenrath", Archetype.QUADRUPED, 3.0F, 450F, 18F, 0.33D, 0x4A4A50, 0x1A1A20, 0xF0F0F0, 0x40C0FF, P_EARS | P_MANE | P_TAIL | P_SPIKES | P_CROWN, new Ability[]{Ability.FEAR_ROAR, Ability.SUMMON, Ability.LEAP_SLAM, Ability.BITE_BLEED, Ability.SHADOW_STEP}, T_FAST, new RegionId[]{RegionId.WOLF_FOREST}, 0, "dire_wolf", true, true));
        add(new MonsterDef("mother_morgra", "Bataklık Anası Morgra", Archetype.BRUTE, 2.5F, 500F, 16F, 0.24D, 0x4A6A40, 0x2A2030, 0xA0A070, 0xA0FF40, P_HOOD | P_TUSKS | P_SPIKES, new Ability[]{Ability.POISON_CLOUD, Ability.SUMMON, Ability.CURSE, Ability.ACID_SPIT}, T_REGEN, new RegionId[]{RegionId.DEAD_MARSH}, 0, "bog_corpse", true, true));
        add(new MonsterDef("dragon_queen_vaelith", "Ejder Kraliçesi Vaelith", Archetype.QUADRUPED, 4.0F, 900F, 24F, 0.3D, 0x8A1010, 0xF0A030, 0xFFE070, 0xFFFF40, P_HORNS | P_WINGS | P_TAIL | P_SPIKES | P_CROWN, new Ability[]{Ability.FIRE_BREATH, Ability.METEOR, Ability.TAIL_SWEEP, Ability.FIRE_NOVA, Ability.DIVE_BOMB}, T_FIRE_IMMUNE | T_FLYING, new RegionId[]{RegionId.DRAGON_TEETH}, 0, null, true, true));
        add(new MonsterDef("pharaoh_sekhmar", "Kum Firavunu Sekhmar", Archetype.HUMANOID, 2.6F, 550F, 18F, 0.26D, 0xE0C060, 0x2050A0, 0xFFF0A0, 0x40C0FF, P_CROWN | P_HOOD, new Ability[]{Ability.SANDSTORM, Ability.SUMMON, Ability.CURSE, Ability.BLINK_BEHIND, Ability.SAND_BLAST}, T_UNDEAD, new RegionId[]{RegionId.GLASS_DESERT}, 0, "mummy", true, true));
        add(new MonsterDef("storm_khan_tengrak", "Fırtına Hanı Tengrak", Archetype.FLYER, 3.2F, 600F, 18F, 0.32D, 0x2A3A7A, 0xE0F0FF, 0xFFE040, 0x80FFFF, P_CROWN | P_TAIL | P_CLAWS, new Ability[]{Ability.THUNDERSTORM, Ability.LIGHTNING_ORB, Ability.DIVE_BOMB, Ability.VORTEX_PULL}, T_FLYING | T_SHOCK_TOUCH, new RegionId[]{RegionId.WHISPER_STEPPE}, 0, null, true, true));
        add(new MonsterDef("crystal_heart_guardian", "Kristal Kalbin Bekçisi", Archetype.GOLEM, 3.5F, 750F, 20F, 0.2D, 0x4A2A7A, 0xC080FF, 0xFFD0FF, 0xFF60FF, P_SPIKES | P_CROWN | P_EYES, new Ability[]{Ability.ARCANE_MISSILES, Ability.SHOCKWAVE, Ability.STONE_SKIN, Ability.QUAKE}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.CRYSTAL_HOLLOW}, 14, null, true, true));
        add(new MonsterDef("lich_king_valdemar", "Lich Kral Valdemar", Archetype.HUMANOID, 2.5F, 650F, 20F, 0.25D, 0x1A1028, 0xD8D0B8, 0x40FFC0, 0x40FFFF, P_CROWN | P_HOOD, new Ability[]{Ability.SHADOW_BOLT, Ability.SUMMON, Ability.DARK_PULSE, Ability.LIFE_DRAIN, Ability.BLINK_BEHIND}, T_UNDEAD, new RegionId[]{RegionId.CURSED_RUINS}, 0, "skeleton_legionary", true, true));
        add(new MonsterDef("deep_kraken", "Derinlerin Krakeni", Archetype.FLOATER, 4.0F, 800F, 20F, 0.24D, 0x5A1A4A, 0xC05080, 0xF0D0E0, 0xFFE000, P_EYES | P_SPIKES | P_CROWN, new Ability[]{Ability.WATER_JET, Ability.VORTEX_PULL, Ability.THUNDERSTORM, Ability.GRAB_THROW}, T_FLOATING | T_AQUATIC, new RegionId[]{RegionId.STORM_COAST}, 0, null, true, true));
        add(new MonsterDef("frost_giant_shade", "Ymir'in Gölgesi", Archetype.BRUTE, 3.6F, 800F, 24F, 0.24D, 0x8AB0D0, 0x2A4A6A, 0xFFFFFF, 0x40C0FF, P_HORNS | P_MANE | P_SPIKES | P_CROWN, new Ability[]{Ability.FROST_NOVA, Ability.ICE_SHARD, Ability.QUAKE, Ability.FROST_BREATH}, T_HEAVY | T_FROST_TOUCH, new RegionId[]{RegionId.YMIRHEIM}, 0, null, true, true));
        add(new MonsterDef("ash_lord_azgaroth", "Kül Lordu Azgaroth", Archetype.BRUTE, 3.5F, 850F, 26F, 0.26D, 0x3A0A06, 0xFF4010, 0x1A1A1A, 0xFFD000, P_HORNS | P_WINGS | P_TAIL | P_SPIKES, new Ability[]{Ability.METEOR, Ability.FIRE_NOVA, Ability.GRAB_THROW, Ability.SUMMON, Ability.ENRAGE}, T_FIRE_IMMUNE | T_HEAVY, new RegionId[]{RegionId.INFERNAX}, 0, "imp", true, true));
        add(new MonsterDef("night_mother_shaelra", "Gece Anası Shaelra", Archetype.ARACHNID, 3.5F, 700F, 20F, 0.3D, 0x1A1028, 0x5A3A9A, 0xE0C0FF, 0xD040FF, P_SPIKES | P_EYES | P_CROWN, new Ability[]{Ability.WEB_SHOT, Ability.SUMMON, Ability.POISON_SPIT, Ability.SHADOW_STEP}, T_NIGHT_ONLY, new RegionId[]{RegionId.NOCTHERA}, 0, "night_weaver", true, true));
        add(new MonsterDef("elder_rot_tree", "Ulu Çürük Ağaç", Archetype.TREANT, 4.0F, 800F, 20F, 0.18D, 0x3A2A1A, 0x5A7A20, 0xD0A040, 0xFF8000, P_SPIKES | P_CROWN, new Ability[]{Ability.ROOTS, Ability.SPORE_BURST, Ability.SUMMON, Ability.SHOCKWAVE}, T_REGEN | T_HEAVY | T_THORNS, new RegionId[]{RegionId.SYLVARIEN}, 0, "angry_sapling", true, true));
        add(new MonsterDef("iron_eater_wurm", "Demir Yiyen Wurm", Archetype.SERPENT, 4.0F, 800F, 22F, 0.26D, 0x5A5050, 0xA06040, 0xE0D0C0, 0xFF2000, P_SPIKES | P_HORNS, new Ability[]{Ability.BURROW, Ability.ACID_SPIT, Ability.QUAKE, Ability.TAIL_SWEEP}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.KHAZDUR}, 10, null, false, true));
        add(new MonsterDef("blood_bull_behemoth", "Kan Boğası Behemot", Archetype.QUADRUPED, 3.5F, 750F, 24F, 0.28D, 0x6A1A10, 0x2A0A06, 0xF0E0D0, 0xFF2000, P_HORNS | P_MANE | P_SPIKES | P_TAIL, new Ability[]{Ability.CHARGE, Ability.QUAKE, Ability.ENRAGE, Ability.FEAR_ROAR}, T_HEAVY, new RegionId[]{RegionId.GORMASH}, 0, null, false, true));
        add(new MonsterDef("spirit_kalkara", "Orman Ruhu Kalkara", Archetype.QUADRUPED, 3.0F, 600F, 20F, 0.36D, 0xF0A020, 0x1A1A10, 0xFFFFFF, 0x80FF40, P_TUSKS | P_TAIL | P_EARS | P_CROWN, new Ability[]{Ability.LEAP_SLAM, Ability.BITE_BLEED, Ability.SUMMON, Ability.INVISIBILITY}, T_FAST, new RegionId[]{RegionId.FELARIS}, 0, "saber_tiger", true, true));
        add(new MonsterDef("black_knight_mordred", "Kara Şövalye Mordred", Archetype.HUMANOID, 2.2F, 650F, 24F, 0.28D, 0x1A1A20, 0x4A0A10, 0xC0A040, 0xFF2020, P_HORNS | P_SPIKES | P_CROWN, new Ability[]{Ability.CHARGE, Ability.SPIN_ATTACK, Ability.DARK_PULSE, Ability.ENRAGE}, T_ARMORED | T_HEAVY, new RegionId[]{RegionId.VALDREN}, 16, null, true, true));
        add(new MonsterDef("golden_dragon_aurelion", "Altın Ejder Aurelion", Archetype.QUADRUPED, 3.8F, 850F, 22F, 0.3D, 0xE0A020, 0xFFF0A0, 0xFFFFFF, 0x40E0FF, P_HORNS | P_WINGS | P_TAIL | P_SPIKES | P_CROWN, new Ability[]{Ability.FIRE_BREATH, Ability.BLIND_FLASH, Ability.METEOR, Ability.HOLY_BOLT}, T_FIRE_IMMUNE | T_FLYING, new RegionId[]{RegionId.MERIDIA}, 0, null, true, true));
        add(new MonsterDef("plague_rat_king", "Veba Kralı Sıçanyüz", Archetype.BRUTE, 2.4F, 450F, 16F, 0.28D, 0x4A4038, 0x7A6A50, 0xE0A0A0, 0xA0FF20, P_EARS | P_TAIL | P_CROWN, new Ability[]{Ability.SUMMON, Ability.POISON_CLOUD, Ability.BITE_BLEED, Ability.DODGE}, T_POISON_TOUCH, new RegionId[]{RegionId.ALDORIA}, 0, "plague_rat", true, true));
        add(new MonsterDef("bone_dragon_nekrath", "Kemik Ejder Nekrath", Archetype.QUADRUPED, 4.0F, 850F, 22F, 0.28D, 0xD8D0B8, 0x2A2A20, 0x40FF80, 0x40FF80, P_HORNS | P_WINGS | P_TAIL | P_SPIKES, new Ability[]{Ability.POISON_BREATH, Ability.SUMMON, Ability.DARK_PULSE, Ability.DIVE_BOMB}, T_UNDEAD | T_FLYING, new RegionId[]{RegionId.CURSED_RUINS}, 0, "bone_hound", true, true));
        add(new MonsterDef("thunder_colossus_thoran", "Yıldırım Kolosu Thoran", Archetype.GOLEM, 3.5F, 750F, 22F, 0.22D, 0x4A4A6A, 0x2A2A3A, 0x80C0FF, 0xA0E0FF, P_SPIKES | P_CROWN, new Ability[]{Ability.THUNDERSTORM, Ability.CHARGE, Ability.SHOCKWAVE, Ability.LIGHTNING_ORB}, T_HEAVY | T_ARMORED | T_SHOCK_TOUCH, new RegionId[]{RegionId.STORM_COAST}, 12, null, true, true));
        add(new MonsterDef("nightmare_rider", "Kabus Süvarisi", Archetype.QUADRUPED, 3.0F, 600F, 20F, 0.36D, 0x101010, 0x3A0A4A, 0xC040FF, 0xFF40FF, P_HORNS | P_MANE | P_TAIL | P_CROWN, new Ability[]{Ability.CHARGE, Ability.FIRE_NOVA, Ability.FEAR_ROAR, Ability.BLINK_BEHIND}, T_FAST | T_FIRE_IMMUNE, new RegionId[]{RegionId.NOCTHERA}, 0, null, true, true));
        add(new MonsterDef("sand_mother_shai", "Kum Anası Shai-Hulud", Archetype.SERPENT, 5.0F, 900F, 24F, 0.28D, 0xD0A868, 0x7A5A30, 0xFFF0D0, 0x401000, P_SPIKES | P_HORNS, new Ability[]{Ability.BURROW, Ability.QUAKE, Ability.SANDSTORM, Ability.SUMMON}, T_HEAVY, new RegionId[]{RegionId.GLASS_DESERT}, 0, "scarab", false, true));
        add(new MonsterDef("crystal_spider_queen", "Kristal Örümcek Kraliçesi", Archetype.ARACHNID, 3.0F, 600F, 18F, 0.3D, 0x7A3AAA, 0xFF90FF, 0xFFFFFF, 0xFFFFFF, P_SPIKES | P_EYES | P_CROWN, new Ability[]{Ability.ARCANE_MISSILES, Ability.WEB_SHOT, Ability.SUMMON, Ability.BLINK_BEHIND}, 0, new RegionId[]{RegionId.CRYSTAL_HOLLOW}, 0, "crystal_spider", true, true));
        add(new MonsterDef("void_watcher_xalthor", "Boşluk Gözcüsü Xal'Thor", Archetype.FLOATER, 3.5F, 700F, 20F, 0.22D, 0x14082A, 0x6A2AAA, 0xFFFFFF, 0xFF00FF, P_EYES | P_SPIKES | P_CROWN, new Ability[]{Ability.DARK_PULSE, Ability.VORTEX_PULL, Ability.BLIND_FLASH, Ability.ARCANE_MISSILES, Ability.BLINK_BEHIND}, T_FLOATING, new RegionId[]{RegionId.NOCTHERA}, 0, null, true, true));
        add(new MonsterDef("stone_titan_golgoth", "Taş Titan Golgoth", Archetype.GOLEM, 4.5F, 1000F, 26F, 0.18D, 0x6A6660, 0x3A3834, 0x90D040, 0xFFA000, P_SPIKES | P_CROWN, new Ability[]{Ability.QUAKE, Ability.ROCK_THROW, Ability.SHOCKWAVE, Ability.STONE_SKIN}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.DRAGON_TEETH}, 16, null, false, true));
        add(new MonsterDef("blood_queen_elizabet", "Kanlı Kraliçe Elizabet", Archetype.HUMANOID, 2.2F, 600F, 20F, 0.3D, 0xE0D0D0, 0x6A0A14, 0x1A0A0A, 0xFF2020, P_WINGS | P_CROWN, new Ability[]{Ability.LIFE_DRAIN, Ability.BLOOD_BOLT, Ability.SUMMON, Ability.SHADOW_STEP}, T_LIFESTEAL | T_FLYING, new RegionId[]{RegionId.CURSED_RUINS, RegionId.VALDREN}, 0, "vampire_bat", true, true));
        add(new MonsterDef("phoenix_anka", "Ateş Kuşu Anka", Archetype.FLYER, 3.0F, 650F, 20F, 0.34D, 0xFF6010, 0xFFD040, 0xFFFFFF, 0xFFFF80, P_CROWN | P_TAIL, new Ability[]{Ability.FIRE_NOVA, Ability.FIREBALL, Ability.DIVE_BOMB, Ability.HEAL}, T_FIRE_IMMUNE | T_FLYING | T_FIRE_TOUCH, new RegionId[]{RegionId.INFERNAX, RegionId.GLASS_DESERT}, 0, null, true, true));
        add(new MonsterDef("marsh_hydra", "Bataklık Hidrası", Archetype.SERPENT, 3.5F, 750F, 20F, 0.26D, 0x2A5A3A, 0x8AA040, 0xF0F0A0, 0xFFE000, P_HORNS | P_SPIKES | P_CROWN, new Ability[]{Ability.POISON_SPIT, Ability.ACID_SPIT, Ability.TAIL_SWEEP, Ability.POISON_BREATH}, T_REGEN | T_AQUATIC, new RegionId[]{RegionId.DEAD_MARSH}, 0, null, true, true));
        add(new MonsterDef("sky_leviathan", "Gök Leviathanı", Archetype.FLYER, 4.5F, 850F, 20F, 0.26D, 0x20406A, 0x80B0E0, 0xFFFFFF, 0x80FFFF, P_TAIL | P_SPIKES | P_CROWN, new Ability[]{Ability.WATER_JET, Ability.VORTEX_PULL, Ability.SONIC_SCREAM, Ability.THUNDERSTORM}, T_FLYING, new RegionId[]{RegionId.STORM_COAST, RegionId.WHISPER_STEPPE}, 0, null, true, true));
        add(new MonsterDef("demon_lord_malakar", "İblis Lordu Malakar", Archetype.BRUTE, 4.2F, 1500F, 30F, 0.28D, 0x2A0606, 0xA01010, 0xFFD040, 0xFF4000, P_HORNS | P_WINGS | P_TAIL | P_SPIKES | P_CROWN, new Ability[]{Ability.METEOR, Ability.DARK_PULSE, Ability.SUMMON, Ability.FIRE_NOVA, Ability.BLINK_BEHIND, Ability.ENRAGE}, T_FIRE_IMMUNE | T_HEAVY | T_ARMORED, new RegionId[]{RegionId.INFERNAX}, 14, "pit_fiend", true, true));
        add(new MonsterDef("mushroom_king_myco", "Mantar Kralı Myco", Archetype.BRUTE, 2.8F, 550F, 16F, 0.22D, 0xE0D0B8, 0xA02090, 0xFFF0FF, 0x60FF60, P_HOOD | P_CROWN, new Ability[]{Ability.SPORE_BURST, Ability.SUMMON, Ability.REGEN_AURA, Ability.POISON_CLOUD}, T_REGEN, new RegionId[]{RegionId.CRYSTAL_HOLLOW}, 0, "mushroom_brute", true, true));
        add(new MonsterDef("clockwork_colossus", "Kurmalı Kolos", Archetype.GOLEM, 4.0F, 850F, 24F, 0.22D, 0xB08A30, 0x4A3A20, 0x40E0FF, 0x40E0FF, P_SPIKES | P_CROWN | P_EYES, new Ability[]{Ability.LIGHTNING_ORB, Ability.CHARGE, Ability.FIRE_NOVA, Ability.SHOCKWAVE}, T_HEAVY | T_ARMORED, new RegionId[]{RegionId.KHAZDUR}, 16, null, true, true));
    }

    private static void spells() {
        spell(new SpellDef("fire_bolt", "Ateş Oku", School.FIRE, SpellShape.BOLT, 6F, 8, 12, 1));
        spell(new SpellDef("fireball", "Ateş Topu", School.FIRE, SpellShape.BALL, 10F, 18, 30, 2));
        spell(new SpellDef("flame_breath", "Alev Nefesi", School.FIRE, SpellShape.CONE, 4F, 3, 2, 2));
        spell(new SpellDef("fire_nova", "Ateş Halkası", School.FIRE, SpellShape.NOVA, 9F, 22, 60, 2));
        spell(new SpellDef("meteor_shower", "Meteor Yağmuru", School.FIRE, SpellShape.RAIN, 12F, 45, 200, 4));
        spell(new SpellDef("fire_wall", "Alev Duvarı", School.FIRE, SpellShape.WALL, 5F, 25, 120, 3));
        spell(new SpellDef("phoenix_blessing", "Anka Kutsaması", School.FIRE, SpellShape.BUFF, 0F, 30, 600, 4));
        spell(new SpellDef("inferno_pillar", "Cehennem Sütunu", School.FIRE, SpellShape.STRIKE, 16F, 35, 140, 4));
        spell(new SpellDef("sun_lance", "Güneş Mızrağı", School.FIRE, SpellShape.BEAM, 3F, 4, 2, 5));
        spell(new SpellDef("ice_shard", "Buz Kıymığı", School.ICE, SpellShape.BOLT, 5F, 7, 10, 1));
        spell(new SpellDef("frost_orb", "Ayaz Küresi", School.ICE, SpellShape.BALL, 8F, 16, 30, 2));
        spell(new SpellDef("cone_of_cold", "Soğuk Konisi", School.ICE, SpellShape.CONE, 3F, 3, 2, 2));
        spell(new SpellDef("frost_nova", "Ayaz Patlaması", School.ICE, SpellShape.NOVA, 7F, 20, 60, 2));
        spell(new SpellDef("blizzard", "Kar Fırtınası", School.ICE, SpellShape.RAIN, 9F, 40, 200, 4));
        spell(new SpellDef("ice_wall", "Buz Duvarı", School.ICE, SpellShape.WALL, 0F, 20, 160, 3));
        spell(new SpellDef("ice_armor", "Buz Zırhı", School.ICE, SpellShape.BUFF, 0F, 25, 500, 3));
        spell(new SpellDef("glacial_spike", "Buzul Dikeni", School.ICE, SpellShape.STRIKE, 14F, 30, 120, 4));
        spell(new SpellDef("absolute_zero", "Mutlak Sıfır", School.ICE, SpellShape.TRAP, 6F, 35, 300, 5));
        spell(new SpellDef("spark", "Kıvılcım", School.LIGHTNING, SpellShape.BOLT, 5F, 6, 8, 1));
        spell(new SpellDef("ball_lightning", "Yumak Şimşek", School.LIGHTNING, SpellShape.BALL, 9F, 18, 40, 2));
        spell(new SpellDef("lightning_beam", "Şimşek Işını", School.LIGHTNING, SpellShape.BEAM, 3F, 4, 2, 3));
        spell(new SpellDef("chain_lightning", "Zincir Şimşek", School.LIGHTNING, SpellShape.CHAIN, 9F, 24, 60, 3));
        spell(new SpellDef("thunderclap", "Gök Gürültüsü", School.LIGHTNING, SpellShape.NOVA, 8F, 22, 70, 2));
        spell(new SpellDef("thunderstorm", "Şimşek Fırtınası", School.LIGHTNING, SpellShape.RAIN, 11F, 45, 220, 4));
        spell(new SpellDef("static_field", "Statik Alan", School.LIGHTNING, SpellShape.AURA, 3F, 30, 400, 3));
        spell(new SpellDef("lightning_step", "Şimşek Adımı", School.LIGHTNING, SpellShape.TELEPORT, 4F, 15, 60, 3));
        spell(new SpellDef("wrath_of_sky", "Göğün Gazabı", School.LIGHTNING, SpellShape.STRIKE, 18F, 40, 180, 5));
        spell(new SpellDef("stone_bullet", "Taş Mermisi", School.EARTH, SpellShape.BOLT, 6F, 7, 12, 1));
        spell(new SpellDef("boulder", "Kaya Fırlatma", School.EARTH, SpellShape.BALL, 11F, 18, 40, 2));
        spell(new SpellDef("earthquake", "Deprem", School.EARTH, SpellShape.NOVA, 9F, 28, 100, 3));
        spell(new SpellDef("stone_wall", "Taş Duvar", School.EARTH, SpellShape.WALL, 0F, 15, 140, 2));
        spell(new SpellDef("stone_skin", "Taş Deri", School.EARTH, SpellShape.BUFF, 0F, 25, 500, 2));
        spell(new SpellDef("earth_spikes", "Toprak Dikenleri", School.EARTH, SpellShape.STRIKE, 12F, 24, 80, 3));
        spell(new SpellDef("quicksand", "Bataklık Tuzağı", School.EARTH, SpellShape.TRAP, 3F, 22, 200, 3));
        spell(new SpellDef("gravity_well", "Yerçekimi Kuyusu", School.EARTH, SpellShape.PULL, 4F, 26, 160, 4));
        spell(new SpellDef("rock_rain", "Kaya Yağmuru", School.EARTH, SpellShape.RAIN, 10F, 40, 200, 4));
        spell(new SpellDef("wind_blade", "Rüzgar Kesiği", School.WIND, SpellShape.BOLT, 5F, 6, 8, 1));
        spell(new SpellDef("gust", "Kasırga Darbesi", School.WIND, SpellShape.CONE, 2F, 10, 30, 1));
        spell(new SpellDef("tornado", "Hortum", School.WIND, SpellShape.PULL, 5F, 30, 160, 3));
        spell(new SpellDef("wind_walk", "Rüzgar Yürüyüşü", School.WIND, SpellShape.BUFF, 0F, 15, 400, 2));
        spell(new SpellDef("feather_fall", "Tüy Düşüşü", School.WIND, SpellShape.AURA, 0F, 10, 300, 1));
        spell(new SpellDef("air_dash", "Hava Atılımı", School.WIND, SpellShape.TELEPORT, 0F, 10, 40, 2));
        spell(new SpellDef("cyclone_nova", "Siklon", School.WIND, SpellShape.NOVA, 7F, 22, 80, 3));
        spell(new SpellDef("storm_arrows", "Fırtına Okları", School.WIND, SpellShape.RAIN, 8F, 35, 180, 4));
        spell(new SpellDef("vacuum_blade", "Boşluk Kılıcı", School.WIND, SpellShape.BEAM, 3F, 4, 2, 5));
        spell(new SpellDef("water_bolt", "Su Oku", School.WATER, SpellShape.BOLT, 5F, 6, 10, 1));
        spell(new SpellDef("bubble_burst", "Kabarcık Patlaması", School.WATER, SpellShape.BALL, 7F, 14, 30, 1));
        spell(new SpellDef("tidal_wave", "Gelgit Dalgası", School.WATER, SpellShape.CONE, 5F, 20, 80, 3));
        spell(new SpellDef("healing_rain", "Şifa Yağmuru", School.WATER, SpellShape.HEAL, 10F, 30, 300, 3));
        spell(new SpellDef("whirlpool", "Girdap", School.WATER, SpellShape.PULL, 5F, 26, 160, 3));
        spell(new SpellDef("water_breath", "Su Solukluğu", School.WATER, SpellShape.BUFF, 0F, 10, 600, 1));
        spell(new SpellDef("hydro_cannon", "Su Topu", School.WATER, SpellShape.BEAM, 3F, 4, 2, 4));
        spell(new SpellDef("drowning_prison", "Boğucu Hapis", School.WATER, SpellShape.TRAP, 6F, 30, 240, 4));
        spell(new SpellDef("purify", "Arındırma", School.WATER, SpellShape.HEAL, 4F, 15, 200, 2));
        spell(new SpellDef("holy_light", "Kutsal Işık", School.LIGHT, SpellShape.BOLT, 6F, 8, 12, 1));
        spell(new SpellDef("heal", "İyileştirme", School.LIGHT, SpellShape.HEAL, 8F, 15, 100, 1));
        spell(new SpellDef("greater_heal", "Büyük Şifa", School.LIGHT, SpellShape.HEAL, 20F, 40, 400, 4));
        spell(new SpellDef("divine_shield", "İlahi Kalkan", School.LIGHT, SpellShape.BUFF, 0F, 35, 700, 4));
        spell(new SpellDef("radiance", "Nur Saçılımı", School.LIGHT, SpellShape.NOVA, 9F, 24, 80, 3));
        spell(new SpellDef("judgement", "Hüküm", School.LIGHT, SpellShape.STRIKE, 16F, 35, 160, 4));
        spell(new SpellDef("blinding_light", "Kör Edici Işık", School.LIGHT, SpellShape.CONE, 2F, 15, 100, 2));
        spell(new SpellDef("sacred_ground", "Kutsal Toprak", School.LIGHT, SpellShape.AURA, 2F, 30, 400, 3));
        spell(new SpellDef("angel_summon", "Melek Çağrısı", School.LIGHT, SpellShape.SUMMON, 0F, 50, 900, 5));
        spell(new SpellDef("shadow_bolt", "Gölge Oku", School.DARK, SpellShape.BOLT, 7F, 8, 12, 1));
        spell(new SpellDef("dark_orb", "Kara Küre", School.DARK, SpellShape.BALL, 10F, 18, 40, 2));
        spell(new SpellDef("life_drain", "Can Emme", School.DARK, SpellShape.BEAM, 2F, 3, 2, 2));
        spell(new SpellDef("curse_of_weakness", "Zayıflık Laneti", School.DARK, SpellShape.CONE, 1F, 15, 100, 2));
        spell(new SpellDef("raise_dead", "Ölüleri Diriltme", School.DARK, SpellShape.SUMMON, 0F, 40, 600, 3));
        spell(new SpellDef("shadow_step", "Gölge Adımı", School.DARK, SpellShape.TELEPORT, 0F, 12, 50, 2));
        spell(new SpellDef("void_nova", "Boşluk Patlaması", School.DARK, SpellShape.NOVA, 10F, 28, 100, 4));
        spell(new SpellDef("black_hole", "Kara Delik", School.DARK, SpellShape.PULL, 6F, 40, 240, 5));
        spell(new SpellDef("cloak_of_shadows", "Gölge Pelerini", School.DARK, SpellShape.BUFF, 0F, 20, 500, 3));
        spell(new SpellDef("thorn_shot", "Diken Atışı", School.NATURE, SpellShape.BOLT, 5F, 6, 10, 1));
        spell(new SpellDef("entangle", "Sarmaşık Tuzağı", School.NATURE, SpellShape.TRAP, 3F, 18, 160, 2));
        spell(new SpellDef("regrowth", "Yeniden Filizlenme", School.NATURE, SpellShape.HEAL, 6F, 15, 160, 1));
        spell(new SpellDef("poison_cloud", "Zehir Bulutu", School.NATURE, SpellShape.BALL, 4F, 18, 80, 2));
        spell(new SpellDef("summon_wolves", "Kurt Çağırma", School.NATURE, SpellShape.SUMMON, 0F, 35, 600, 3));
        spell(new SpellDef("barkskin", "Ağaç Kabuğu", School.NATURE, SpellShape.BUFF, 0F, 20, 500, 2));
        spell(new SpellDef("natures_wrath", "Doğanın Gazabı", School.NATURE, SpellShape.RAIN, 9F, 38, 200, 4));
        spell(new SpellDef("spore_nova", "Spor Patlaması", School.NATURE, SpellShape.NOVA, 6F, 20, 80, 2));
        spell(new SpellDef("treant_call", "Ağaç Adam Çağrısı", School.NATURE, SpellShape.SUMMON, 0F, 50, 900, 5));
        spell(new SpellDef("magic_missile", "Büyü Füzesi", School.ARCANE, SpellShape.BOLT, 4F, 4, 6, 1));
        spell(new SpellDef("arcane_orb", "Gizem Küresi", School.ARCANE, SpellShape.BALL, 9F, 18, 35, 2));
        spell(new SpellDef("blink", "Işınlanma", School.ARCANE, SpellShape.TELEPORT, 0F, 12, 40, 2));
        spell(new SpellDef("arcane_beam", "Gizem Işını", School.ARCANE, SpellShape.BEAM, 3F, 4, 2, 3));
        spell(new SpellDef("mana_shield", "Mana Kalkanı", School.ARCANE, SpellShape.BUFF, 0F, 25, 500, 3));
        spell(new SpellDef("arcane_explosion", "Gizem Patlaması", School.ARCANE, SpellShape.NOVA, 9F, 24, 70, 3));
        spell(new SpellDef("time_slow", "Zamanı Yavaşlatma", School.ARCANE, SpellShape.AURA, 0F, 40, 600, 4));
        spell(new SpellDef("arcane_barrage", "Gizem Yağmuru", School.ARCANE, SpellShape.RAIN, 10F, 40, 200, 4));
        spell(new SpellDef("telekinesis", "Telekinezi", School.ARCANE, SpellShape.PULL, 2F, 14, 80, 2));
        spell(new SpellDef("starfall", "Yıldız Düşüşü", School.ARCANE, SpellShape.STRIKE, 20F, 50, 240, 5));
        spell(new SpellDef("blood_spear", "Kan Mızrağı", School.BLOOD, SpellShape.BOLT, 9F, 4, 14, 2));
        spell(new SpellDef("blood_boil", "Kan Kaynatma", School.BLOOD, SpellShape.NOVA, 10F, 10, 80, 3));
        spell(new SpellDef("sanguine_pact", "Kan Antlaşması", School.BLOOD, SpellShape.BUFF, 0F, 5, 600, 3));
        spell(new SpellDef("hemorrhage", "Kanama", School.BLOOD, SpellShape.CONE, 3F, 12, 80, 2));
        spell(new SpellDef("blood_ritual", "Kan Ayini", School.BLOOD, SpellShape.HEAL, 12F, 25, 400, 4));
        spell(new SpellDef("crimson_rain", "Kızıl Yağmur", School.BLOOD, SpellShape.RAIN, 10F, 30, 200, 4));
        spell(new SpellDef("vein_chain", "Damar Zinciri", School.BLOOD, SpellShape.CHAIN, 8F, 18, 60, 3));
        spell(new SpellDef("blood_golem", "Kan Golemi", School.BLOOD, SpellShape.SUMMON, 0F, 40, 900, 5));
        spell(new SpellDef("spirit_arrow", "Ruh Oku", School.SPIRIT, SpellShape.BOLT, 6F, 7, 10, 1));
        spell(new SpellDef("soul_orb", "Ruh Küresi", School.SPIRIT, SpellShape.BALL, 9F, 16, 35, 2));
        spell(new SpellDef("ancestral_guard", "Ataların Koruması", School.SPIRIT, SpellShape.BUFF, 0F, 30, 600, 3));
        spell(new SpellDef("spirit_wolves", "Ruh Kurtları", School.SPIRIT, SpellShape.SUMMON, 0F, 30, 500, 3));
        spell(new SpellDef("soul_link", "Ruh Bağı", School.SPIRIT, SpellShape.CHAIN, 7F, 20, 60, 3));
        spell(new SpellDef("banish", "Sürgün", School.SPIRIT, SpellShape.STRIKE, 14F, 30, 140, 4));
        spell(new SpellDef("ghost_walk", "Hayalet Yürüyüşü", School.SPIRIT, SpellShape.TELEPORT, 0F, 15, 80, 3));
        spell(new SpellDef("wail_of_souls", "Ruhların Feryadı", School.SPIRIT, SpellShape.NOVA, 9F, 26, 90, 4));
        spell(new SpellDef("spirit_beam", "Ruh Işını", School.SPIRIT, SpellShape.BEAM, 3F, 4, 2, 4));
    }

    private static void swords() {
        SWORDS.add(new SwordDef("rusty_shortsword", "Paslı Kısa Kılıç", 1F, -2.2F, 0, 0x8A6A50, 0x5A4A3A, 0x4A3020, -1, SwordPassive.NONE, SwordSkill.CRESCENT_SLASH));
        SWORDS.add(new SwordDef("militia_sword", "Milis Kılıcı", 1F, -2.4F, 1, 0xC0C0C0, 0x7A6A50, 0x5A3A20, -1, SwordPassive.NONE, SwordSkill.WAR_CRY));
        SWORDS.add(new SwordDef("aldorian_longsword", "Aldoria Uzun Kılıcı", 2F, -2.4F, 2, 0xE0E0E8, 0xE0B040, 0x2A3A8A, 0x3060FF, SwordPassive.CRIT, SwordSkill.CRESCENT_SLASH));
        SWORDS.add(new SwordDef("knight_oath", "Şövalye Yemini", 3F, -2.4F, 3, 0xF0F0F8, 0xF0C040, 0x8A1A1A, 0xFF3030, SwordPassive.HOLY, SwordSkill.ROYAL_DECREE));
        SWORDS.add(new SwordDef("elven_moonblade", "Elf Ay Kılıcı", 3F, -2.0F, 3, 0xD0F0FF, 0xC0E0D0, 0x2A5A4A, 0x80FFFF, SwordPassive.MANA_STEAL, SwordSkill.WIND_CUTTER));
        SWORDS.add(new SwordDef("dwarven_runeblade", "Cüce Rün Kılıcı", 4F, -2.6F, 3, 0xA0A0A8, 0xC08030, 0x4A2A10, 0xFF8000, SwordPassive.KNOCKUP, SwordSkill.EARTH_SPLITTER));
        SWORDS.add(new SwordDef("orc_cleaver", "Ork Satırı", 5F, -3.0F, 2, 0x7A7A70, 0x4A3020, 0x2A1A10, -1, SwordPassive.BLEED, SwordSkill.BERSERK));
        SWORDS.add(new SwordDef("giant_greatsword", "Dev Kılıcı", 7F, -3.2F, 3, 0xB0B8C0, 0x6A7080, 0x3A3A3A, 0x60A0FF, SwordPassive.GIANT_SLAYER, SwordSkill.GROUND_SLAM));
        SWORDS.add(new SwordDef("demon_fang", "İblis Dişi", 4F, -2.2F, 4, 0x3A0A0A, 0xA01010, 0x1A1A1A, 0xFF4000, SwordPassive.WITHER, SwordSkill.VOID_RIFT));
        SWORDS.add(new SwordDef("flame_tongue", "Alev Dili", 3F, -2.4F, 3, 0xFF6010, 0x4A1A0A, 0x2A0A06, 0xFFD040, SwordPassive.BURN, SwordSkill.FLAME_WAVE));
        SWORDS.add(new SwordDef("frostmourne", "Ayaz Yası", 4F, -2.4F, 4, 0x90D0FF, 0x30405A, 0x1A2030, 0x60FFFF, SwordPassive.FREEZE, SwordSkill.ICE_PRISON));
        SWORDS.add(new SwordDef("stormcaller", "Fırtına Çağıran", 4F, -2.2F, 4, 0xA0C0FF, 0x3A4A8A, 0x1A2040, 0xFFFFFF, SwordPassive.SHOCK, SwordSkill.THUNDER_STRIKE));
        SWORDS.add(new SwordDef("viper_fang", "Engerek Dişi", 2F, -1.8F, 2, 0x60C040, 0x2A4A20, 0x1A2A10, 0xA0FF40, SwordPassive.POISON, SwordSkill.POISON_FAN));
        SWORDS.add(new SwordDef("bloodthirster", "Kan Emici", 4F, -2.2F, 4, 0xA01020, 0x2A0A0A, 0x1A0A0A, 0xFF2040, SwordPassive.LIFESTEAL, SwordSkill.BLOOD_FRENZY));
        SWORDS.add(new SwordDef("shadow_edge", "Gölge Kenarı", 3F, -1.9F, 3, 0x2A1A3A, 0x5A3A8A, 0x101018, 0xC040FF, SwordPassive.BLIND, SwordSkill.SHADOW_DASH));
        SWORDS.add(new SwordDef("dawnbreaker", "Şafak Kıran", 5F, -2.4F, 4, 0xFFF0C0, 0xFFD040, 0xE0E0E0, 0xFFFFA0, SwordPassive.UNDEAD_SLAYER, SwordSkill.SUN_BURST));
        SWORDS.add(new SwordDef("dragonbane", "Ejderha Kıran", 6F, -2.8F, 5, 0xE0D0B0, 0x8A1A10, 0x3A1A10, 0xFF6000, SwordPassive.DRAGON_SLAYER, SwordSkill.DRAGON_BREATH));
        SWORDS.add(new SwordDef("soul_reaper", "Ruh Biçen", 5F, -2.6F, 4, 0x60FFE0, 0x1A3A3A, 0x0A1A1A, 0xD0FFF8, SwordPassive.EXECUTE, SwordSkill.SOUL_REAP));
        SWORDS.add(new SwordDef("tempest_katana", "Kasırga Katanası", 3F, -1.8F, 4, 0xE0F0F0, 0x2A2A2A, 0x8A1A1A, 0x80FFD0, SwordPassive.CRIT, SwordSkill.BLADE_STORM));
        SWORDS.add(new SwordDef("whirlwind_saber", "Kasırga Palası", 3F, -2.0F, 3, 0xD0E0E0, 0x6A8A8A, 0x2A3A3A, 0xA0FFFF, SwordPassive.SLOW, SwordSkill.WHIRLWIND));
        SWORDS.add(new SwordDef("crystal_sword", "Kristal Kılıç", 4F, -2.2F, 4, 0xE0A0FF, 0x8040C0, 0x3A1A5A, 0xFFFFFF, SwordPassive.MANA_STEAL, SwordSkill.STAR_FALL));
        SWORDS.add(new SwordDef("bone_blade", "Kemik Kılıç", 3F, -2.4F, 2, 0xE8E0C8, 0x5A5040, 0x2A2A20, 0x40FF80, SwordPassive.WITHER, SwordSkill.SPIRIT_ARMY));
        SWORDS.add(new SwordDef("tide_blade", "Gelgit Kılıcı", 3F, -2.2F, 3, 0x40A0FF, 0x206080, 0x103040, 0x80FFFF, SwordPassive.SLOW, SwordSkill.TIDE_SLASH));
        SWORDS.add(new SwordDef("meteor_hammer_blade", "Meteor Kılıcı", 6F, -3.0F, 4, 0x5A3A2A, 0xFF6010, 0x2A1A10, 0xFFA040, SwordPassive.BURN, SwordSkill.METEOR_DROP));
        SWORDS.add(new SwordDef("phantom_rapier", "Hayalet Meç", 2F, -1.6F, 3, 0xC0E0FF, 0xA0A0C0, 0x3A3A5A, 0x80C0FF, SwordPassive.CRIT, SwordSkill.PHANTOM_BLADES));
        SWORDS.add(new SwordDef("mirror_blade", "Ayna Kılıcı", 3F, -2.0F, 4, 0xF0F0FF, 0xC0C0D0, 0x5A5A6A, 0xFFFFFF, SwordPassive.BLIND, SwordSkill.MIRROR_CLONES));
        SWORDS.add(new SwordDef("thunder_fang", "Gök Dişi", 3F, -2.0F, 3, 0xFFE040, 0x3A3A6A, 0x1A1A2A, 0xA0E0FF, SwordPassive.SHOCK, SwordSkill.CHAIN_SHOCK));
        SWORDS.add(new SwordDef("life_bloom", "Hayat Çiçeği", 2F, -2.2F, 3, 0x80E060, 0xF0A0C0, 0x3A6A2A, 0xFFC0E0, SwordPassive.NONE, SwordSkill.LIFE_BLOOM));
        SWORDS.add(new SwordDef("executioner", "Cellat Kılıcı", 7F, -3.2F, 4, 0x6A6A70, 0x2A2A2A, 0x3A0A0A, 0xFF0000, SwordPassive.EXECUTE, SwordSkill.EXECUTION));
        SWORDS.add(new SwordDef("ashbringer", "Kül Getiren", 5F, -2.6F, 5, 0xD0C8C0, 0x4A3A3A, 0x2A1A1A, 0xFF8040, SwordPassive.DEMON_SLAYER, SwordSkill.ASH_CYCLONE));
        SWORDS.add(new SwordDef("gravity_edge", "Yerçekimi Kılıcı", 5F, -2.8F, 5, 0x3A2A5A, 0x1A1A2A, 0x0A0A1A, 0xA060FF, SwordPassive.WEAKEN, SwordSkill.GRAVITY_CRUSH));
        SWORDS.add(new SwordDef("crown_of_kings", "Kralların Kılıcı", 6F, -2.4F, 5, 0xFFF0D0, 0xFFD040, 0x5A1A8A, 0xFF40FF, SwordPassive.HOLY, SwordSkill.ROYAL_DECREE));
        SWORDS.add(new SwordDef("starfall_blade", "Yıldız Kılıcı", 5F, -2.2F, 5, 0x2A3A8A, 0xE0E0FF, 0x1A1A3A, 0xFFFFFF, SwordPassive.MANA_STEAL, SwordSkill.STAR_FALL));
        SWORDS.add(new SwordDef("wind_cutter", "Rüzgar Kesen", 3F, -1.8F, 3, 0xE0FFF0, 0x80C0A0, 0x2A4A3A, 0xC0FFE0, SwordPassive.KNOCKUP, SwordSkill.WIND_CUTTER));
        SWORDS.add(new SwordDef("void_reaver", "Boşluk Yağmacısı", 6F, -2.6F, 5, 0x1A0A2A, 0x6A2AAA, 0x0A0A0A, 0xFF00FF, SwordPassive.WITHER, SwordSkill.VOID_RIFT));
    }
}
