// GENERATED by gen/realm/mobs.py - do not edit by hand
package com.krolasyon.bosses.realm.entity;

import com.krolasyon.bosses.realm.Faction;

import java.util.List;

public final class GenSpecs {
    private GenSpecs() {}

    public static final MobSpec ASH_WALKER = new MobSpec("ash_walker", Faction.ASH, MobSpec.Kind.GROUND, 0.8F, 1.95F, 30, 5, 2, 0.25, 0.0, 0.0, false, 10,
            "minecraft:entity.husk.ambient", "minecraft:entity.husk.hurt", "minecraft:entity.husk.death", "minecraft:entity.husk.step", 0.75F, 0x3A3634, 0xFF7A20,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 2.6F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 120, 4F, 10F, 1.2F, 2.5F, 1, Ability.Element.FIRE, "", 2));

    public static final MobSpec EMBER_HOUND = new MobSpec("ember_hound", Faction.ASH, MobSpec.Kind.GROUND, 1.0F, 1.1F, 24, 5, 1, 0.33, 0.0, 0.0, true, 10,
            "minecraft:entity.wolf.growl", "minecraft:entity.wolf.hurt", "minecraft:entity.wolf.death", "minecraft:entity.wolf.step", 0.7F, 0x2A1210, 0xFF6A10,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 16, 0F, 2.4F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.LEAP, 3, 22, 8, 90, 3F, 11F, 1.0F, 2.2F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.BREATH, 4, 32, 6, 140, 0F, 6F, 0.8F, 0.0F, 1, Ability.Element.FIRE, "", 3));

    public static final MobSpec MAGMA_TORTOISE = new MobSpec("magma_tortoise", Faction.ASH, MobSpec.Kind.GROUND, 1.6F, 1.3F, 60, 7, 12, 0.16, 0.8, 8, true, 20,
            "minecraft:entity.turtle.ambient_land", "minecraft:entity.turtle.hurt_baby", "minecraft:entity.turtle.death", "minecraft:entity.ravager.step", 0.5F, 0x3A1A10, 0xFFA020,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 24, 0F, 2.8F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.BOMB, 3, 24, 11, 70, 4F, 18F, 1.1F, 2.8F, 2, Ability.Element.FIRE, "", 4),
            new Ability(Ability.Type.SHIELD, 4, 32, 16, 260, 0F, 8F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 1),
            new Ability(Ability.Type.SLAM, 4, 32, 16, 160, 0F, 4F, 1.0F, 4F, 1, Ability.Element.FIRE, "", 2));

    public static final MobSpec ASH_KNIGHT = new MobSpec("ash_knight", Faction.ASH, MobSpec.Kind.GROUND, 0.9F, 2.1F, 40, 7, 8, 0.24, 0.3, 0.0, false, 15,
            "minecraft:entity.wither_skeleton.ambient", "minecraft:entity.wither_skeleton.hurt", "minecraft:entity.wither_skeleton.death", "minecraft:entity.iron_golem.step", 0.8F, 0x262020, 0xFF7A20,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 3.0F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 10, 140, 5F, 14F, 1.3F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.SHIELD, 3, 24, 11, 300, 0F, 10F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 1));

    public static final MobSpec FLAME_DJINN = new MobSpec("flame_djinn", Faction.ASH, MobSpec.Kind.FLYING, 0.9F, 2.0F, 30, 5, 2, 0.28, 0.0, 9, true, 15,
            "minecraft:entity.blaze.ambient", "minecraft:entity.blaze.hurt", "minecraft:entity.blaze.death", "", 0.8F, 0xFF6A10, 0xFFE070,
            new Ability(Ability.Type.BOLT, 3, 24, 11, 40, 3F, 20F, 1.1F, 1.5F, 3, Ability.Element.FIRE, "", 5),
            new Ability(Ability.Type.BLINK, 3, 24, 11, 140, 0F, 12F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 1),
            new Ability(Ability.Type.NOVA, 4, 32, 16, 160, 0F, 7F, 0.9F, 1.2F, 10, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 2.2F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 2));

    public static final MobSpec CINDER_BEETLE = new MobSpec("cinder_beetle", Faction.ASH, MobSpec.Kind.GROUND, 0.7F, 0.6F, 12, 3, 4, 0.3, 0.0, 0.0, true, 6,
            "minecraft:entity.silverfish.ambient", "minecraft:entity.silverfish.hurt", "minecraft:entity.silverfish.death", "minecraft:entity.silverfish.step", 0.6F, 0x1A1210, 0xFF6A10,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 16, 0F, 1.8F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.EXPLODE, 4, 32, 26, 10, 0F, 2.2F, 2.6F, 3.0F, 1, Ability.Element.FIRE, "", 6));

    public static final MobSpec BLOODSUCKER = new MobSpec("bloodsucker", Faction.BLOOD, MobSpec.Kind.FLYING, 0.9F, 0.9F, 18, 4, 0, 0.32, 0.0, 0, false, 10,
            "minecraft:entity.bat.ambient", "minecraft:entity.bat.hurt", "minecraft:entity.bat.death", "", 0.6F, 0x3A0610, 0xC02030,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 2.2F, 1.0F, 0.0F, 1, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.DRAIN, 4, 32, 4, 120, 0F, 7F, 0.8F, 0.0F, 1, Ability.Element.BLOOD, "", 3));

    public static final MobSpec BLOOD_GUARD = new MobSpec("blood_guard", Faction.BLOOD, MobSpec.Kind.GROUND, 0.85F, 2.2F, 40, 7, 6, 0.25, 0.0, 0.0, false, 15,
            "minecraft:entity.vindicator.ambient", "minecraft:entity.vindicator.hurt", "minecraft:entity.vindicator.death", "minecraft:entity.iron_golem.step", 0.75F, 0x4A0812, 0xE0B040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 3.8F, 1.0F, 0.0F, 1, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.SPIN, 4, 32, 4, 160, 0F, 4F, 0.9F, 4F, 1, Ability.Element.BLOOD, "", 3));

    public static final MobSpec FLESH_ABOMINATION = new MobSpec("flesh_abomination", Faction.BLOOD, MobSpec.Kind.GROUND, 1.7F, 1.8F, 70, 8, 3, 0.18, 0.6, 6, false, 25,
            "minecraft:entity.slime.squish", "minecraft:entity.slime.hurt", "minecraft:entity.slime.death", "minecraft:entity.slime.jump", 0.5F, 0x7A1018, 0xFFD040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 24, 0F, 3.2F, 1.0F, 0.0F, 1, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.BOMB, 3, 24, 11, 80, 4F, 16F, 0.9F, 2.5F, 2, Ability.Element.BLOOD, "", 4),
            new Ability(Ability.Type.SUMMON, 4, 32, 16, 300, 0F, 16F, 1.0F, 0.0F, 2, Ability.Element.BLOOD, "blood_leech", 2));

    public static final MobSpec BLOOD_LEECH = new MobSpec("blood_leech", Faction.BLOOD, MobSpec.Kind.GROUND, 0.6F, 0.5F, 14, 3, 1, 0.27, 0.0, 0.0, false, 5,
            "minecraft:entity.silverfish.ambient", "minecraft:entity.silverfish.hurt", "minecraft:entity.silverfish.death", "minecraft:entity.silverfish.step", 0.5F, 0x4A0410, 0xFF8090,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 14, 0F, 1.8F, 1.0F, 0.0F, 1, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 70, 2F, 8F, 1.0F, 1.8F, 1, Ability.Element.BLOOD, "", 3));

    public static final MobSpec BLOOD_WITCH = new MobSpec("blood_witch", Faction.BLOOD, MobSpec.Kind.GROUND, 0.8F, 2.0F, 30, 5, 1, 0.24, 0.0, 10, false, 15,
            "minecraft:entity.witch.ambient", "minecraft:entity.witch.hurt", "minecraft:entity.witch.death", "", 0.9F, 0x2A000A, 0xFF3040,
            new Ability(Ability.Type.BOLT, 3, 24, 11, 50, 3F, 20F, 1.2F, 0.0F, 2, Ability.Element.BLOOD, "", 5),
            new Ability(Ability.Type.HEAL, 3, 24, 11, 220, 0F, 20F, 1.0F, 10F, 1, Ability.Element.BLOOD, "", 2),
            new Ability(Ability.Type.ERUPT, 4, 40, 20, 160, 3F, 14F, 1.1F, 0.0F, 8, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 2.2F, 0.6F, 0.0F, 1, Ability.Element.BLOOD, "", 1));

    public static final MobSpec BONE_SPIDER = new MobSpec("bone_spider", Faction.BLOOD, MobSpec.Kind.GROUND, 1.4F, 0.9F, 28, 5, 3, 0.3, 0.0, 0.0, false, 10,
            "minecraft:entity.spider.ambient", "minecraft:entity.spider.hurt", "minecraft:entity.spider.death", "minecraft:entity.spider.step", 0.7F, 0xD4C8B0, 0xFF2030,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 16, 0F, 2.4F, 1.0F, 0.0F, 1, Ability.Element.POISON, "", 3),
            new Ability(Ability.Type.WEB, 3, 24, 11, 100, 3F, 12F, 0.6F, 0.0F, 1, Ability.Element.BONE, "", 3),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 120, 4F, 12F, 1.0F, 2.4F, 1, Ability.Element.POISON, "", 3));

    public static final MobSpec SHADOW_ASSASSIN = new MobSpec("shadow_assassin", Faction.SHADOW, MobSpec.Kind.GROUND, 0.8F, 2.0F, 26, 7, 2, 0.31, 0.0, 0.0, false, 15,
            "minecraft:entity.enderman.ambient", "minecraft:entity.enderman.hurt", "minecraft:entity.enderman.death", "", 1.3F, 0x120A1E, 0xA050FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 14, 0F, 2.6F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.VANISH, 3, 24, 11, 240, 6F, 20F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 2),
            new Ability(Ability.Type.BLINK, 3, 24, 11, 100, 5F, 18F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.SPIN, 4, 24, 3, 140, 0F, 3.5F, 0.8F, 3.5F, 1, Ability.Element.SHADOW, "", 3));

    public static final MobSpec VOID_WATCHER = new MobSpec("void_watcher", Faction.SHADOW, MobSpec.Kind.FLYING, 1.1F, 1.2F, 34, 5, 4, 0.22, 0.0, 10, false, 15,
            "minecraft:entity.guardian.ambient", "minecraft:entity.guardian.hurt", "minecraft:entity.guardian.death", "", 0.6F, 0x1E1230, 0xA040FF,
            new Ability(Ability.Type.BEAM, 4, 48, 8, 120, 3F, 16F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 4),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 50, 3F, 20F, 1.0F, 0.0F, 2, Ability.Element.SHADOW, "", 4),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 2.0F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 1));

    public static final MobSpec NIGHTMARE_STEED = new MobSpec("nightmare_steed", Faction.SHADOW, MobSpec.Kind.GROUND, 1.3F, 1.9F, 44, 7, 3, 0.34, 0.4, 0.0, false, 15,
            "minecraft:entity.skeleton_horse.ambient", "minecraft:entity.skeleton_horse.hurt", "minecraft:entity.skeleton_horse.death", "minecraft:entity.horse.gallop", 0.7F, 0x0E0818, 0xD070FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 2.8F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 8, 110, 5F, 18F, 1.3F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.ROAR, 3, 24, 11, 240, 0F, 8F, 1.0F, 8F, 1, Ability.Element.SHADOW, "", 1));

    public static final MobSpec WHISPERER = new MobSpec("whisperer", Faction.SHADOW, MobSpec.Kind.FLYING, 0.8F, 2.0F, 24, 6, 0, 0.27, 0.0, 0.0, false, 12,
            "minecraft:entity.vex.ambient", "minecraft:entity.vex.hurt", "minecraft:entity.vex.death", "", 0.6F, 0x3A1A5A, 0xFFFFFF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 16, 0F, 2.6F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.AURA, 3, 24, 11, 160, 0F, 6F, 0.6F, 6F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.BLINK, 3, 24, 11, 120, 4F, 16F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 2));

    public static final MobSpec CRYSTAL_GOLEM = new MobSpec("crystal_golem", Faction.SHADOW, MobSpec.Kind.GROUND, 1.6F, 2.6F, 90, 11, 14, 0.2, 0.9, 0.0, false, 30,
            "minecraft:entity.iron_golem.hurt", "minecraft:block.amethyst_block.break", "minecraft:entity.iron_golem.death", "minecraft:entity.iron_golem.step", 0.6F, 0x1E1230, 0xB070FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 26, 0F, 3.4F, 1.0F, 0.0F, 1, Ability.Element.CRYSTAL, "", 3),
            new Ability(Ability.Type.SLAM, 4, 32, 16, 140, 0F, 5F, 1.2F, 5F, 1, Ability.Element.CRYSTAL, "", 3),
            new Ability(Ability.Type.ERUPT, 3, 24, 11, 160, 4F, 16F, 1.1F, 0.0F, 10, Ability.Element.CRYSTAL, "", 3));

    public static final MobSpec SHADOW_SCORPION = new MobSpec("shadow_scorpion", Faction.SHADOW, MobSpec.Kind.GROUND, 1.3F, 1.0F, 34, 6, 6, 0.27, 0.0, 0.0, false, 14,
            "minecraft:entity.spider.ambient", "minecraft:entity.spider.hurt", "minecraft:entity.spider.death", "minecraft:entity.spider.step", 0.5F, 0x150A26, 0xC070FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 2.8F, 1.0F, 0.0F, 1, Ability.Element.POISON, "", 3),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 70, 3F, 14F, 0.9F, 0.0F, 1, Ability.Element.POISON, "", 3),
            new Ability(Ability.Type.WEB, 4, 32, 16, 140, 0F, 5F, 0.6F, 0.0F, 1, Ability.Element.SHADOW, "", 2));

    public static final MobSpec LEGION_FOOTSOLDIER = new MobSpec("legion_footsoldier", Faction.LEGION, MobSpec.Kind.GROUND, 0.8F, 1.7F, 30, 6, 7, 0.26, 0.0, 0.0, false, 12,
            "minecraft:entity.piglin_brute.ambient", "minecraft:entity.piglin_brute.hurt", "minecraft:entity.piglin_brute.death", "minecraft:entity.piglin_brute.step", 1.3F, 0x46464C, 0xC02A20,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 3.3F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 8, 160, 4F, 12F, 1.2F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.SHIELD, 3, 24, 11, 300, 0F, 10F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 1));

    public static final MobSpec LEGION_ARCHER = new MobSpec("legion_archer", Faction.LEGION, MobSpec.Kind.GROUND, 0.7F, 1.65F, 24, 4, 3, 0.26, 0.0, 12, false, 10,
            "minecraft:entity.piglin.ambient", "minecraft:entity.piglin.hurt", "minecraft:entity.piglin.death", "minecraft:entity.piglin.step", 1.4F, 0x4A2E14, 0xFFD040,
            new Ability(Ability.Type.BOLT, 2, 16, 7, 30, 4F, 22F, 1.4F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 6),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 120, 4F, 22F, 1.0F, 0.0F, 3, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 2.0F, 0.6F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 1));

    public static final MobSpec WAR_BULL = new MobSpec("war_bull", Faction.LEGION, MobSpec.Kind.GROUND, 1.8F, 1.9F, 70, 10, 8, 0.27, 0.8, 0.0, false, 25,
            "minecraft:entity.ravager.ambient", "minecraft:entity.ravager.hurt", "minecraft:entity.ravager.death", "minecraft:entity.ravager.step", 0.8F, 0x2A160C, 0xC08A24,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 22, 0F, 3.2F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 8, 100, 5F, 20F, 1.5F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 4),
            new Ability(Ability.Type.SLAM, 3, 24, 11, 160, 0F, 4.5F, 1.0F, 4.5F, 1, Ability.Element.BRIMSTONE, "", 2));

    public static final MobSpec BRIMSTONE_MORTAR = new MobSpec("brimstone_mortar", Faction.LEGION, MobSpec.Kind.GROUND, 1.3F, 2.0F, 60, 6, 10, 0.18, 0.7, 12, true, 25,
            "minecraft:entity.iron_golem.hurt", "minecraft:entity.iron_golem.damage", "minecraft:entity.iron_golem.death", "minecraft:entity.iron_golem.step", 0.9F, 0x46464C, 0xFFD040,
            new Ability(Ability.Type.BOMB, 3, 24, 11, 50, 5F, 26F, 1.3F, 3.2F, 2, Ability.Element.BRIMSTONE, "", 6),
            new Ability(Ability.Type.SLAM, 4, 32, 16, 120, 0F, 4F, 1.0F, 4F, 1, Ability.Element.BRIMSTONE, "", 2),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 24, 0F, 2.8F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 1));

    public static final MobSpec CHAIN_DEMON = new MobSpec("chain_demon", Faction.LEGION, MobSpec.Kind.GROUND, 1.0F, 2.3F, 55, 9, 5, 0.25, 0.4, 0.0, false, 20,
            "minecraft:entity.zoglin.ambient", "minecraft:entity.zoglin.hurt", "minecraft:entity.zoglin.death", "minecraft:entity.zoglin.step", 0.7F, 0x3A0A08, 0x8A8A94,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 22, 0F, 3.4F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.PULL, 3, 24, 11, 120, 4F, 14F, 0.8F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 4),
            new Ability(Ability.Type.SPIN, 4, 32, 4, 160, 0F, 4.5F, 0.9F, 4.5F, 1, Ability.Element.BRIMSTONE, "", 2));

    public static final MobSpec IRON_SENTINEL = new MobSpec("iron_sentinel", Faction.LEGION, MobSpec.Kind.GROUND, 1.4F, 2.8F, 80, 12, 16, 0.2, 1.0, 0.0, false, 30,
            "minecraft:entity.iron_golem.hurt", "minecraft:entity.iron_golem.damage", "minecraft:entity.iron_golem.death", "minecraft:entity.iron_golem.step", 0.6F, 0x26262A, 0xFFB020,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 24, 0F, 4.2F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.SPIN, 4, 32, 4, 150, 0F, 5F, 1.0F, 5F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.SHIELD, 3, 24, 11, 300, 0F, 12F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 1));

    public static final MobSpec INFERNAL_IMP = new MobSpec("infernal_imp", Faction.LEGION, MobSpec.Kind.GROUND, 0.6F, 1.2F, 16, 4, 1, 0.3, 0.0, 0.0, true, 6,
            "minecraft:entity.vex.ambient", "minecraft:entity.vex.hurt", "minecraft:entity.vex.death", "", 1.3F, 0x9A2A14, 0xFFE040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 14, 0F, 2.0F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 60, 3F, 14F, 0.9F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 90, 3F, 9F, 1.0F, 2F, 1, Ability.Element.FIRE, "", 3));

    public static final MobSpec SOUL_PRIEST = new MobSpec("soul_priest", Faction.SOUL, MobSpec.Kind.GROUND, 0.8F, 2.05F, 28, 4, 1, 0.23, 0.0, 10, false, 15,
            "minecraft:entity.evoker.ambient", "minecraft:entity.evoker.hurt", "minecraft:entity.evoker.death", "", 0.8F, 0x0A2A32, 0x40E0FF,
            new Ability(Ability.Type.BOLT, 3, 24, 11, 50, 3F, 20F, 1.1F, 0.0F, 2, Ability.Element.SOUL, "", 5),
            new Ability(Ability.Type.HEAL, 3, 24, 11, 220, 0F, 20F, 1.0F, 10F, 1, Ability.Element.SOUL, "", 2),
            new Ability(Ability.Type.SUMMON, 4, 32, 16, 320, 0F, 20F, 1.0F, 0.0F, 2, Ability.Element.SOUL, "skull_swarm", 2));

    public static final MobSpec PHANTOM_KNIGHT = new MobSpec("phantom_knight", Faction.SOUL, MobSpec.Kind.GROUND, 0.9F, 2.15F, 36, 7, 6, 0.27, 0.0, 0.0, false, 15,
            "minecraft:entity.skeleton.ambient", "minecraft:entity.skeleton.hurt", "minecraft:entity.skeleton.death", "minecraft:entity.skeleton.step", 0.6F, 0x60B8C8, 0xFFFFFF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 3.6F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 8, 120, 5F, 16F, 1.3F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.BLINK, 3, 24, 11, 160, 6F, 18F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 1));

    public static final MobSpec SOUL_EATER = new MobSpec("soul_eater", Faction.SOUL, MobSpec.Kind.GROUND, 1.4F, 1.6F, 50, 8, 4, 0.3, 0.0, 0.0, false, 20,
            "minecraft:entity.skeleton_horse.ambient", "minecraft:entity.wolf.hurt", "minecraft:entity.skeleton.death", "minecraft:entity.skeleton.step", 0.5F, 0xD4C8B0, 0x40E0FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 2.8F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.DRAIN, 4, 32, 4, 140, 0F, 8F, 0.8F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.ROAR, 3, 24, 11, 200, 0F, 8F, 1.0F, 8F, 1, Ability.Element.SOUL, "", 2));

    public static final MobSpec SKULL_SWARM = new MobSpec("skull_swarm", Faction.SOUL, MobSpec.Kind.FLYING, 0.6F, 0.6F, 10, 3, 0, 0.3, 0.0, 6, false, 5,
            "minecraft:entity.skeleton.ambient", "minecraft:entity.skeleton.hurt", "minecraft:entity.skeleton.death", "", 1.6F, 0xF4ECDC, 0x40E0FF,
            new Ability(Ability.Type.BOLT, 3, 24, 11, 40, 2F, 16F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 4),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 16, 0F, 1.6F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 2));

    public static final MobSpec BELL_BEARER = new MobSpec("bell_bearer", Faction.SOUL, MobSpec.Kind.GROUND, 1.4F, 2.6F, 85, 10, 8, 0.19, 0.9, 0.0, false, 30,
            "minecraft:entity.warden.ambient", "minecraft:entity.warden.hurt", "minecraft:entity.warden.death", "minecraft:entity.warden.step", 1.2F, 0x264046, 0xFFE080,
            new Ability(Ability.Type.STUN, 3, 24, 11, 140, 0F, 7F, 0.8F, 7F, 1, Ability.Element.SOUL, "", 4),
            new Ability(Ability.Type.SLAM, 4, 32, 16, 160, 0F, 5F, 1.2F, 5F, 1, Ability.Element.SOUL, "", 2),
            new Ability(Ability.Type.MELEE, 2, 16, 7, 26, 0F, 3.6F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 3));

    public static final MobSpec BONE_SERPENT = new MobSpec("bone_serpent", Faction.SOUL, MobSpec.Kind.GROUND, 1.3F, 1.4F, 60, 9, 6, 0.24, 0.5, 0.0, false, 25,
            "minecraft:entity.skeleton.ambient", "minecraft:entity.skeleton.hurt", "minecraft:entity.skeleton.death", "minecraft:entity.skeleton.step", 0.4F, 0xD4C8B0, 0x1A7AA0,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 3.2F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.BREATH, 4, 32, 6, 140, 0F, 8F, 0.8F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 90, 4F, 18F, 1.0F, 0.0F, 3, Ability.Element.BONE, "", 2));

    public static final MobSpec THRONE_GARGOYLE = new MobSpec("throne_gargoyle", null, MobSpec.Kind.FLYING, 1.2F, 1.2F, 40, 7, 10, 0.3, 0.5, 0.0, false, 15,
            "minecraft:entity.phantom.ambient", "minecraft:entity.phantom.hurt", "minecraft:entity.phantom.death", "", 0.6F, 0x363030, 0xFF3020,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 2.6F, 1.0F, 0.0F, 1, Ability.Element.BONE, "", 3),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 100, 3F, 12F, 1.3F, 3F, 1, Ability.Element.BONE, "", 2));

    public static final MobSpec MAGMA_WORM = new MobSpec("magma_worm", null, MobSpec.Kind.GROUND, 1.4F, 1.5F, 55, 9, 6, 0.22, 0.6, 0.0, true, 20,
            "minecraft:entity.magma_cube.squish", "minecraft:entity.magma_cube.hurt", "minecraft:entity.magma_cube.death", "", 0.5F, 0x2A1210, 0xFFE070,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 3.2F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.BREATH, 4, 32, 6, 120, 0F, 8F, 0.9F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.ERUPT, 3, 24, 11, 140, 3F, 14F, 1.0F, 0.0F, 8, Ability.Element.FIRE, "", 2));

    public static final MobSpec CRIMSON_REVENANT = new MobSpec("crimson_revenant", null, MobSpec.Kind.GROUND, 0.95F, 2.2F, 55, 10, 10, 0.25, 0.4, 0.0, false, 25,
            "minecraft:entity.wither_skeleton.ambient", "minecraft:entity.wither_skeleton.hurt", "minecraft:entity.wither_skeleton.death", "minecraft:entity.iron_golem.step", 0.7F, 0x7A0A12, 0xFFD040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 22, 0F, 3.6F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 120, 4F, 14F, 1.3F, 3.2F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.ROAR, 3, 24, 11, 260, 0F, 10F, 1.0F, 10F, 1, Ability.Element.FIRE, "", 1));

    public static final MobSpec ASH_ENVOY = new MobSpec("ash_envoy", Faction.ASH, MobSpec.Kind.ENVOY, 0.8F, 2.0F, 40, 2, 2, 0.22, 0.0, 0.0, false, 0,
            "minecraft:entity.villager.ambient", "minecraft:entity.villager.hurt", "minecraft:entity.villager.death", "", 0.7F, 0x5A4434, 0xFF8A20);

    public static final MobSpec BLOOD_ENVOY = new MobSpec("blood_envoy", Faction.BLOOD, MobSpec.Kind.ENVOY, 0.8F, 2.0F, 40, 2, 2, 0.22, 0.0, 0.0, false, 0,
            "minecraft:entity.villager.ambient", "minecraft:entity.villager.hurt", "minecraft:entity.villager.death", "", 0.7F, 0x5A0612, 0xFF2030);

    public static final MobSpec SHADOW_ENVOY = new MobSpec("shadow_envoy", Faction.SHADOW, MobSpec.Kind.ENVOY, 0.8F, 2.0F, 40, 2, 2, 0.22, 0.0, 0.0, false, 0,
            "minecraft:entity.villager.ambient", "minecraft:entity.villager.hurt", "minecraft:entity.villager.death", "", 0.7F, 0x221436, 0xC060FF);

    public static final MobSpec LEGION_ENVOY = new MobSpec("legion_envoy", Faction.LEGION, MobSpec.Kind.ENVOY, 0.8F, 2.0F, 40, 2, 2, 0.22, 0.0, 0.0, false, 0,
            "minecraft:entity.villager.ambient", "minecraft:entity.villager.hurt", "minecraft:entity.villager.death", "", 0.7F, 0x6A1A14, 0xFFD040);

    public static final MobSpec SOUL_ENVOY = new MobSpec("soul_envoy", Faction.SOUL, MobSpec.Kind.ENVOY, 0.8F, 2.0F, 40, 2, 2, 0.22, 0.0, 0.0, false, 0,
            "minecraft:entity.villager.ambient", "minecraft:entity.villager.hurt", "minecraft:entity.villager.death", "", 0.7F, 0x145060, 0x40E0FF);

    public static final MobSpec VARKHAS = new MobSpec("varkhas", Faction.ASH, MobSpec.Kind.LORD, 1.4F, 4.0F, 420, 16, 14, 0.28, 0.9, 0.0, true, 400,
            "minecraft:entity.wither_skeleton.ambient", "minecraft:entity.iron_golem.hurt", "minecraft:entity.wither.death", "minecraft:entity.iron_golem.step", 0.5F, 0x262020, 0xFFB020,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 22, 0F, 4.4F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.ERUPT, 3, 24, 11, 140, 3F, 20F, 0.9F, 2F, 12, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.METEOR, 3, 48, 11, 260, 4F, 26F, 0.9F, 6F, 8, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.SLAM, 4, 32, 16, 160, 0F, 6F, 1.2F, 6.5F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 10, 200, 6F, 18F, 1.2F, 0.0F, 1, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.SUMMON, 3, 24, 11, 500, 0F, 30F, 1.0F, 0.0F, 2, Ability.Element.FIRE, "ash_knight", 1));

    public static final MobSpec SERATHIS = new MobSpec("serathis", Faction.BLOOD, MobSpec.Kind.LORD, 1.2F, 4.0F, 360, 13, 8, 0.3, 0.7, 0.0, false, 400,
            "minecraft:entity.witch.ambient", "minecraft:entity.witch.hurt", "minecraft:entity.wither.death", "", 0.7F, 0x500A14, 0xE0B040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 3.6F, 1.0F, 0.0F, 1, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 60, 3F, 24F, 0.9F, 0.0F, 5, Ability.Element.BLOOD, "", 4),
            new Ability(Ability.Type.DRAIN, 4, 48, 6, 160, 0F, 12F, 0.9F, 0.0F, 1, Ability.Element.BLOOD, "", 3),
            new Ability(Ability.Type.BLINK, 3, 24, 11, 140, 4F, 24F, 1.0F, 0.0F, 1, Ability.Element.BLOOD, "", 2),
            new Ability(Ability.Type.SUMMON, 3, 24, 11, 360, 0F, 30F, 1.0F, 0.0F, 3, Ability.Element.BLOOD, "bloodsucker", 1),
            new Ability(Ability.Type.ERUPT, 3, 24, 11, 180, 3F, 18F, 1.0F, 2F, 10, Ability.Element.BLOOD, "", 2));

    public static final MobSpec NYXAR = new MobSpec("nyxar", Faction.SHADOW, MobSpec.Kind.LORD, 1.3F, 3.8F, 340, 12, 8, 0.3, 0.6, 0.0, false, 400,
            "minecraft:entity.illusioner.ambient", "minecraft:entity.illusioner.hurt", "minecraft:entity.illusioner.death", "", 0.6F, 0x120A1E, 0xD090FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 18, 0F, 3.4F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 50, 3F, 26F, 0.85F, 0.0F, 6, Ability.Element.SHADOW, "", 4),
            new Ability(Ability.Type.BLINK, 3, 24, 11, 110, 3F, 26F, 1.0F, 0.0F, 1, Ability.Element.SHADOW, "", 3),
            new Ability(Ability.Type.AURA, 3, 24, 11, 200, 0F, 8F, 0.8F, 8F, 1, Ability.Element.SHADOW, "", 2),
            new Ability(Ability.Type.BEAM, 4, 36, 8, 200, 4F, 20F, 1.1F, 0.0F, 1, Ability.Element.SHADOW, "", 2),
            new Ability(Ability.Type.SUMMON, 3, 24, 11, 400, 0F, 30F, 1.0F, 0.0F, 2, Ability.Element.SHADOW, "shadow_assassin", 1),
            new Ability(Ability.Type.NOVA, 4, 36, 18, 220, 0F, 10F, 0.9F, 1.5F, 16, Ability.Element.SHADOW, "", 2));

    public static final MobSpec GROMMAK = new MobSpec("grommak", Faction.LEGION, MobSpec.Kind.LORD, 1.8F, 4.1F, 480, 18, 16, 0.27, 1.0, 0.0, false, 400,
            "minecraft:entity.ravager.ambient", "minecraft:entity.ravager.hurt", "minecraft:entity.ravager.death", "minecraft:entity.ravager.step", 0.6F, 0x46464C, 0xFFD040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 24, 0F, 4.4F, 1.0F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.SLAM, 4, 32, 16, 140, 0F, 7F, 1.2F, 7F, 1, Ability.Element.BRIMSTONE, "", 3),
            new Ability(Ability.Type.CHARGE, 4, 32, 10, 180, 6F, 20F, 1.3F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 2),
            new Ability(Ability.Type.PULL, 3, 24, 11, 160, 5F, 18F, 0.7F, 0.0F, 1, Ability.Element.BRIMSTONE, "", 2),
            new Ability(Ability.Type.ROAR, 3, 24, 11, 300, 0F, 14F, 1.0F, 14F, 1, Ability.Element.BRIMSTONE, "", 1),
            new Ability(Ability.Type.SUMMON, 3, 24, 11, 420, 0F, 30F, 1.0F, 0.0F, 3, Ability.Element.BRIMSTONE, "legion_footsoldier", 1),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 200, 6F, 22F, 1.4F, 5F, 1, Ability.Element.BRIMSTONE, "", 2));

    public static final MobSpec ILVAINE = new MobSpec("ilvaine", Faction.SOUL, MobSpec.Kind.LORD, 1.2F, 3.8F, 340, 11, 8, 0.27, 0.7, 0.0, false, 400,
            "minecraft:entity.evoker.ambient", "minecraft:entity.evoker.hurt", "minecraft:entity.wither.death", "", 0.6F, 0x0A2A32, 0x80F0FF,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 20, 0F, 3.4F, 1.0F, 0.0F, 1, Ability.Element.SOUL, "", 3),
            new Ability(Ability.Type.BOLT, 3, 24, 11, 50, 3F, 24F, 0.9F, 0.0F, 4, Ability.Element.SOUL, "", 4),
            new Ability(Ability.Type.SUMMON, 3, 24, 11, 300, 0F, 30F, 1.0F, 0.0F, 3, Ability.Element.SOUL, "skull_swarm", 2),
            new Ability(Ability.Type.HEAL, 3, 24, 11, 400, 0F, 30F, 1.2F, 10F, 1, Ability.Element.SOUL, "", 1),
            new Ability(Ability.Type.STUN, 4, 36, 18, 180, 0F, 8F, 0.8F, 8F, 1, Ability.Element.SOUL, "", 2),
            new Ability(Ability.Type.ERUPT, 3, 24, 11, 160, 3F, 20F, 1.0F, 2F, 12, Ability.Element.SOUL, "", 2),
            new Ability(Ability.Type.NOVA, 4, 36, 18, 200, 0F, 10F, 0.9F, 1.2F, 14, Ability.Element.SOUL, "", 2));

    public static final MobSpec AZGAROTH = new MobSpec("azgaroth", null, MobSpec.Kind.TYRANT, 2.0F, 5.2F, 900, 22, 18, 0.3, 1.0, 0.0, true, 1000,
            "minecraft:entity.ender_dragon.growl", "minecraft:entity.wither.hurt", "minecraft:entity.ender_dragon.death", "minecraft:entity.ravager.step", 0.6F, 0x6A0E10, 0xFFD040,
            new Ability(Ability.Type.MELEE, 2, 16, 7, 22, 0F, 5.2F, 1.0F, 0.0F, 1, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.METEOR, 3, 56, 11, 220, 4F, 30F, 0.9F, 7F, 12, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.ERUPT, 3, 24, 11, 140, 3F, 22F, 0.9F, 2F, 14, Ability.Element.FIRE, "", 3),
            new Ability(Ability.Type.BREATH, 4, 40, 6, 200, 0F, 10F, 0.8F, 0.0F, 1, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.LEAP, 4, 32, 16, 200, 6F, 24F, 1.4F, 6F, 1, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.SUMMON, 3, 24, 11, 420, 0F, 30F, 1.0F, 0.0F, 2, Ability.Element.FIRE, "crimson_revenant", 1),
            new Ability(Ability.Type.NOVA, 4, 32, 16, 180, 0F, 12F, 0.8F, 1.5F, 18, Ability.Element.FIRE, "", 2),
            new Ability(Ability.Type.DRAIN, 4, 40, 6, 260, 0F, 12F, 0.9F, 0.0F, 1, Ability.Element.BLOOD, "", 1));

    public static final List<MobSpec> ALL = List.of(ASH_WALKER, EMBER_HOUND, MAGMA_TORTOISE, ASH_KNIGHT, FLAME_DJINN, CINDER_BEETLE, BLOODSUCKER, BLOOD_GUARD, FLESH_ABOMINATION, BLOOD_LEECH, BLOOD_WITCH, BONE_SPIDER, SHADOW_ASSASSIN, VOID_WATCHER, NIGHTMARE_STEED, WHISPERER, CRYSTAL_GOLEM, SHADOW_SCORPION, LEGION_FOOTSOLDIER, LEGION_ARCHER, WAR_BULL, BRIMSTONE_MORTAR, CHAIN_DEMON, IRON_SENTINEL, INFERNAL_IMP, SOUL_PRIEST, PHANTOM_KNIGHT, SOUL_EATER, SKULL_SWARM, BELL_BEARER, BONE_SERPENT, THRONE_GARGOYLE, MAGMA_WORM, CRIMSON_REVENANT, ASH_ENVOY, BLOOD_ENVOY, SHADOW_ENVOY, LEGION_ENVOY, SOUL_ENVOY, VARKHAS, SERATHIS, NYXAR, GROMMAK, ILVAINE, AZGAROTH);
}
