package com.krolasyon.bosses.realm.entity;

import com.krolasyon.bosses.realm.Faction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.ForgeRegistries;

import javax.annotation.Nullable;

/** gameplay description of one realm creature (generated by gen/realm/mobs.py into GenSpecs) */
public record MobSpec(String id, @Nullable Faction faction, Kind kind, float width, float height, double health, double damage, double armor,
                      double speed, double knockbackResist, double preferRange, boolean fireImmune, int xp,
                      String ambient, String hurt, String death, String step, float pitch, int eggA, int eggB, Ability... abilities) {

    public enum Kind { GROUND, FLYING, ENVOY, LORD, TYRANT }

    public boolean flying() { return kind == Kind.FLYING; }

    public boolean boss() { return kind == Kind.LORD || kind == Kind.TYRANT; }

    @Nullable
    public static SoundEvent sound(String id) {
        if (id == null || id.isEmpty()) return null;
        return ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(id));
    }
}
