// GENERATED by gen/build_mobs.py - do not edit by hand
package com.krolasyon.bosses.entity.mob;

import com.krolasyon.bosses.faction.Faction;

import java.util.Map;

final class MobSpecTable {
    private MobSpecTable() {}

    static void fill(Map<String, MobSpec> m) {
        m.put("cinder_imp", new MobSpec("cinder_imp", Faction.EMBER)
                .stats(22, 1, 3.5, 0.24)
                .size(0.8F, 1.4F, 1.0F).fly(2.2).reach(2.2).anim(2.6, 2.6).voice("demon", 1.7F).egg(0x2A1E1A, 0xFF8A1E).spawn(10, 2, 4, "ember_wastes", "ashen_barrens").xp(6, 22)
                .ab(Ab.of(Ab.Kind.MELEE, "attack").time(14, 7).cd(18).dmg(1.0F).p(0.3, 0).color(0xFF7A1A).fx("flame"))
                .ab(Ab.of(Ab.Kind.BOLT, "spit").time(20, 10).cd(70).w(4).range(4, 18).dmg(1.4F).p(1.0, 0).color(0xFF8A22).fx("flame").los())
                .ab(Ab.of(Ab.Kind.DIVE, "dive").time(26, 8, 18).cd(150).w(3).range(5, 16).dmg(1.6F).p(1.25, 0.8).color(0xFF5A10).fx("flame").air()));
    }
}
