modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="krolasyonvocations"
version="1.0.0"
displayName="Krolasyon Vocations"
authors="krolasyon"
description='''
Dort meslek seti: Elite Knight, Royal Paladin, Elder Druid ve Master Sorcerer.
Zirh, silah, kolye, yuzuk ve mermi; tum parcalar set bonusu ve ozel etkiler verir.
'''

[[dependencies.krolasyonvocations]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.krolasyonvocations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
